"greetd" functions added

diff --git a/init/ashrc b/init/ashrc
--- a/init/ashrc
+++ b/init/ashrc
@@ -1,32 +1,17 @@
-#! /bin/sh
+#! /bin/Sh
 # set -x
 # Definition sequence
 # doas.conf->share->/etc/profile->login shell->.profile->.ashrc->env
 
-alias /='eval'
-# bash does not recognize //
-alias //='lineno="$LINENO"'
-
 SCRIPT_NAME="ashrc" && export SCRIPT_NAME
 
-# share folder initialization
-[ ! -z "${SHARE_PREFIX:+x}" ] || {
-	[ -d "/mnt/init" ] &&
-	{ SHARE_PREFIX="/mnt" && export SHARE_PREFIX; } || {
-		[ -d "/opt/init" ] &&
-		{ SHARE_PREFIX="/opt" && export SHARE_PREFIX; } ||
-		printf '%s %s\n' '$SHARE_PREFIX' "not found"
-	}
-}
-
-_functions="$SHARE_PREFIX/init/functions"
-[ ! -f "$_functions" ] && {
-	printf '%s %s\n' '$_functions' "'$_functions' does not exist"
-	exit 0
+[ ! -z "$(type "env_reset" > /dev/null && type "env_reset")" ] ||
+{
+	[ -f "/mnt/init/include/route" ] &&
+	. /mnt/init/include/route
 } || {
-	env_reset_type="$(type "env_reset" > /dev/null 2>&1 && type "env_reset")" || :
-	[ ! -z "${env_reset_type:+x}" ] ||
-		. "$_functions"
+	printf '%s %s\n' '$env_reset' "'$env_reset' could not get defined"
+	exit 0
 }
 
 # : ${UID="$(id -u)"} && export UID
@@ -52,11 +37,11 @@ reset_cursor_shape() {
 		echo 0 | tee $cursor_blink_key
 	}
 	# || {
-	# 	[ ! -f "$cursor_blink_key" ] ||
-	# 	[ "$(cat $cursor_blink_key)" -eq "0" ] || {
-	# 		! command -v "/usr/bin/doas" > /dev/null 2>&1 ||
-	# 		echo 0 | doas -u root -- tee /sys/class/graphics/fbcon/cursor_blink
-	# 	}
+	#   [ ! -f "$cursor_blink_key" ] ||
+	#   [ "$(cat $cursor_blink_key)" -eq "0" ] || {
+	#       ! command -v "/usr/bin/doas" > /dev/null 2>&1 ||
+	#       echo 0 | doas -u root -- tee /sys/class/graphics/fbcon/cursor_blink
+	#   }
 	# }
 # reset
 # printf '%s %s\n' '$TERM' "$TERM"
@@ -391,7 +376,7 @@ reset_cursor_shape() {
 reset_cursor_shape
 
 [ -z "${SHELL_DEBUG+x}" ] || echo "In $HOME/.ashrc"
-#
+
 # tabstop
 tabs -4
 LESS="-x4" && export LESS
@@ -405,6 +390,50 @@ LESS="-x4" && export LESS
 		. ${SHARE_PREFIX}/init/kiss-env
 }
 
+sock_sway=
+launcher="greeter"
+
+sway_socket() {
+	local launcher="${1-}"
+	[ -z "${launcher:+x}" ] ||
+	printf '%s %s\n' '$launcher' "$launcher"
+	# sock_id="$(ps -ef | grep "sway -d" | grep -v grep | \
+	#   grep -v swc-launch | awk "{print \$1}" | tr -d " ")"
+	# sock_id_list="$(ps -ef | grep "sway -d" | grep -v grep | \
+	#   grep -v swc-launch | sort -rnk3 | awk "{print \$1}" | tr -d " ")"
+	# # local index=0
+	# for sock_id in $sock_id_list; do
+	#    break
+	# done
+	[ -z "${WAYLAND_DISPLAY+x}" ] || {
+		printf '%s %s\n' '$SHLVL' "$SHLVL" >> ${WAYLAND_CONFIG_HOME}/.autolauncher.log 2>&1
+		printf '%s %s\n' '$WAYLAND_DISPLAY' "$WAYLAND_DISPLAY" >> ${WAYLAND_CONFIG_HOME}/.autolauncher.log 2>&1
+		export WAYLAND_DISPLAY
+		printf '%s' "${WAYLAND_DISPLAY}" > $HOME/.wayland_display
+		[ -d "/tmp/wayland" ] || \mkdir -p "/tmp/wayland"
+		printf '%s' "${WAYLAND_DISPLAY}" > /tmp/wayland/.display
+	}
+	sock_id="$(for item in $( \
+	ps -ef | grep "sway -d" | grep -v "grep" | awk "{print \$2}" 2> /dev/null)
+	do
+		[ -z "$(pstree -p "$item" | grep "$item" | grep "sway" 2> /dev/null)" ] &&
+		continue || { printf '%s' "$item"; break; }
+	done)"
+
+	[ -n "${sock_id:+x}" ] || { printf '\n'; return 0; }
+
+	SWAY_SOCK="$XDG_RUNTIME_DIR/sway-ipc.$UID.$sock_id.sock"
+	[ ! -S "$SWAY_SOCK" ] || {
+		export SWAY_SOCK
+		[ -d "/tmp/wayland" ] || mkdir -p "/tmp/wayland"
+		printf '%s' "${SWAY_SOCK}" > /tmp/wayland/.socket
+
+		printf '%s %s\n' '$SWAY_SOCK' "$(cat "/tmp/wayland/.socket" 2> /dev/null)"
+	}
+	[ -z "${DISPLAY+x}" ] || unset DISPLAY
+	printf '\n%s' "$SWAY_SOCK"
+}
+
 # printf '%s %s\n' '$WAYLAND_DISPLAY' "$WAYLAND_DISPLAY"
 # printf '%s %s\n' '$DISPLAY' "$DISPLAY"
 
@@ -413,13 +442,20 @@ LESS="-x4" && export LESS
 # tty_nme might not a number on pts
 tty_num="$(tty | sed -e 's/.*tty\(.*\)/\1/')"
 # export tty_num
-#
+
+[ -z "${IS_KISS+x}" ] || DONT_USE_GREET=
+[ -z "${DONT_USE_GREET=x}" ] && designate_tty=7 ||
+designate_tty=1
+
 # Initialize wayland
 # [ "$XDG_SESSION_TYPE" = "wayland" ] ||
 [ ! -d "${SHARE_PREFIX}/init" ] ||
 # [ ! -z "${DISPLAY+x}" ] ||
-[ ! -z "${WAYLAND_DISPLAY+x}" ] ||
-[ "1" != "$tty_num" ] || {
+{
+	[ ! -z "${WAYLAND_DISPLAY+x}" ] &&
+	[ ! -z "${WAYLAND_ENV+x}" ]
+} ||
+[ "$designate_tty" != "$tty_num" ] || {
 # sway can boot as root
 # [ "$UID" -eq "0" ] || { # [ "$(id -nu)" = "root" ] || {
 	# https://discourse.ubuntu.com/t/environment-variables-for-wayland-hackers/12750
@@ -427,22 +463,25 @@ tty_num="$(tty | sed -e 's/.*tty\(.*\)/\1/')"
 	# https://stackoverflow.com/questions/41736528/linux-wayland-display-multiple-user
 	# XDG_RUNTIME_DIR defined in $HOME/.xdg_runtime_dir and sourced in ${SHARE_PREFIX}/init/env
 	# [ "$UID" -eq "0" ] || {
-	[ -d "/tmp/wayland" ] || mkdir -p "/tmp/wayland"
+	[ -d "/tmp/wayland" ] || \mkdir -p "/tmp/wayland"
 	# [ -e "/tmp/wayland/.display" ] || touch "/tmp/wayland/.display"
-	[ -n "${WAYLAND_CONFIG_HOME:+x}" ] ||
-	WAYLAND_CONFIG_HOME="${XDG_CONFIG_HOME:-$HOME/.config}/wayland"
-	export WAYLAND_CONFIG_HOME
+	[ -n "${WAYLAND_CONFIG_HOME:+x}" ] || {
+		WAYLAND_CONFIG_HOME="${XDG_CONFIG_HOME:-$HOME/.config}/wayland"
+		export WAYLAND_CONFIG_HOME
+	}
 	printf '%s %s\n' '$SHLVL' "$SHLVL" |
 		tee -a ${WAYLAND_CONFIG_HOME}/.autolauncher.log 2>&1
 	# }
 
 	# sway_socket
-	sock_sway="$([ ! -f "/tmp/wayland/.socket" ] ||
-		cat "/tmp/wayland/.socket" 2> /dev/null)"
-	# {
-	# [ -z "${sock_sway:+x}" ] ||
-	[ ! -S "$sock_sway" ] &&
-		# } &&
+	# sock_sway="$([ ! -f "/tmp/wayland/.socket" ] ||
+	#   cat "/tmp/wayland/.socket" 2> /dev/null)"
+	sock_sway="$(delegate -- sway_socket "$launcher")"
+
+	{
+		[ -z "${sock_sway:+x}" ] ||
+		[ ! -S "$sock_sway" ]
+	} &&
 	# ${SHARE_PREFIX}/init/velox-launch
 	# { . ${SHARE_PREFIX}/init/sway-launch; sock_sway=sway_socket "$launcher"; } ||
 	. ${SHARE_PREFIX}/init/sway-launch ||
@@ -461,14 +500,19 @@ tty_num="$(tty | sed -e 's/.*tty\(.*\)/\1/')"
 #     [ "$UID" -ne "0" ]; then
 
 # [ "$UID" -eq "0" ] ||
-[ "1" != "$tty_num" ] || {
+[ "$designate_tty" != "$tty_num" ] || {
+	[ -d "/tmp/wayland" ] || \mkdir -p "/tmp/wayland"
+	[ -n "${WAYLAND_CONFIG_HOME:+x}" ] || {
+		WAYLAND_CONFIG_HOME="${XDG_CONFIG_HOME:-$HOME/.config}/wayland"
+		export WAYLAND_CONFIG_HOME
+	}
 
 	# [ ! -z "${WAYLAND_DISPLAY+x}" ] || {
 	#   WAYLAND_DISPLAY="$(cat /tmp/wayland/.display 2> /dev/null)"
 	#   [ -z "${WAYLAND_DISPLAY+x}" ] || export WAYLAND_DISPLAY
 	# }
 	# {
-	#
+
 	# Writting WAYLAND_DISPLAY to file
 	display_wayland="$([ ! -f "/tmp/wayland/.display" ] ||
 		cat "/tmp/wayland/.display" 2> /dev/null)"
@@ -490,7 +534,8 @@ tty_num="$(tty | sed -e 's/.*tty\(.*\)/\1/')"
 	}
 
 	# Reading SWAY_SOCK from file
-	sock_sway="$([ ! -f "/tmp/wayland/.socket" ] || cat "/tmp/wayland/.socket" 2> /dev/null)"
+	# sock_sway="$([ ! -f "/tmp/wayland/.socket" ] || cat "/tmp/wayland/.socket" 2> /dev/null)"
+	sock_sway="$(delegate -- sway_socket "$launcher")"
 	# Try again
 	# {
 	#   # [ -f "/tmp/wayland/.socket" ] &&
@@ -504,6 +549,14 @@ tty_num="$(tty | sed -e 's/.*tty\(.*\)/\1/')"
 	[ "$sock_sway" = "$SWAY_SOCK" ] ||
 		{ SWAY_SOCK="$sock_sway"; export SWAY_SOCK; }
 	# }
+	[ ! -z "${WAYLAND_ENV+x}" ] ||
+		[ ! -f "${WAYLAND_CONFIG_HOME}/env" ] || {
+		printf '%s %s\n' "${WAYLAND_CONFIG_HOME}/env" "sourced"
+			set -a
+			# shellcheck disable=SC1090
+			. "${WAYLAND_CONFIG_HOME}/env"
+			set +a
+		}
 }
 
 # elif [ -n "$(cat /tmp/wayland/.display)" ] && [ -z ${WAYLAND_DISPLAY+x} ]; then
diff --git a/init/bin/s b/init/bin/s
--- a/init/bin/s
+++ b/init/bin/s
@@ -3,16 +3,41 @@
 # . s
 # Definition sequence
 # doas.conf->share->/etc/profile->login shell->.profile->.ashrc->env
-#
-# share folder initialization
-if [ -d "/mnt/init" ]; then
-	SHARE_PREFIX="/mnt" && export SHARE_PREFIX
-elif [ -d "/opt/init" ]; then
-	SHARE_PREFIX="/opt" && export SHARE_PREFIX
-fi
 
+SCRIPT_NAME="s" && export SCRIPT_NAME
+
+[ ! -z "$(type "env_reset" > /dev/null && type "env_reset")" ] ||
+{
+	[ -f "/mnt/init/include/route" ] &&
+	. /mnt/init/include/route
+} || {
+	printf '%s %s\n' '$env_reset' "'$env_reset' could not get defined"
+	exit 0
+}
+
+# # share folder initialization
+# [ ! -z "${SHARE_PREFIX:+x}" ] || {
+#   [ -d "/mnt/init" ] &&
+#   { SHARE_PREFIX="/mnt" && export SHARE_PREFIX; } || {
+#       [ -d "/opt/init" ] &&
+#       { SHARE_PREFIX="/opt" && export SHARE_PREFIX; } ||
+#       printf '%s %s\n' '$SHARE_PREFIX' "not found"
+#   }
+# }
+#
+# _functions="/usr/include/kiss/functions"
+# [ -f "$_functions" ] ||
+# _functions="$SHARE_PREFIX/init/include/functions"
+# [ ! -f "$_functions" ] && {
+#   printf '%s %s\n' '$_functions' "'$_functions' does not exist"
+#   exit 0
+# } || {
+#   env_reset_type="$(type "env_reset" > /dev/null 2>&1 && type "env_reset")" || :
+#   [ ! -z "${env_reset_type:+x}" ] ||
+#       . "$_functions"
+# }
+
+# . $SHARE_PREFIX/init/etc/profile.d/share
 . /mnt/init/etc/profile.d/share
 . /etc/profile
-# . $SHARE_PREFIX/init/etc/profile.d/share
-# . /etc/profile
 . $SHARE_PREFIX/init/profile
diff --git a/init/env b/init/env
--- a/init/env
+++ b/init/env
@@ -3,32 +3,15 @@
 # Definition sequence
 # doas.conf->share->/etc/profile->login shell->.profile->.ashrc->env
 
-newline="
-"
-
-alias /='eval'
-alias //='lineno="$LINENO"'
-
 SCRIPT_NAME="env" && export SCRIPT_NAME
 
-# share folder initialization
-[ ! -z "${SHARE_PREFIX:+x}" ] || {
-	[ -d "/mnt/init" ] &&
-	{ SHARE_PREFIX="/mnt" && export SHARE_PREFIX; } || {
-		[ -d "/opt/init" ] &&
-		{ SHARE_PREFIX="/opt" && export SHARE_PREFIX; } ||
-		printf '%s %s\n' '$SHARE_PREFIX' "not found"
-	}
-}
-
-_functions="$SHARE_PREFIX/init/functions"
-[ ! -f "$_functions" ] && {
-	printf '%s %s\n' '$_functions' "'$_functions' does not exist"
-	exit 0
+[ ! -z "$(type "env_reset" > /dev/null && type "env_reset")" ] ||
+{
+	[ -f "/mnt/init/include/route" ] &&
+	. /mnt/init/include/route
 } || {
-	env_reset_type="$(type "env_reset" > /dev/null 2>&1 && type "env_reset")" || :
-	[ ! -z "${env_reset_type:+x}" ] ||
-		. "$_functions"
+	printf '%s %s\n' '$env_reset' "'$env_reset' could not get defined"
+	exit 0
 }
 
 // env_reset "IFS" " $(printf '%s' "t" | tr 't' "\\t")${newline}"
@@ -99,6 +82,7 @@ set_font() {
 { [ "$TERM" != "linux" ] && [ -n "${TERM##*"vt"*}" ]; } ||
 [ -n "${TMUX+x}" ] || set_font
 
+[ ! -d "/usr/share/easy-rsa" ] ||
 path_prepend PATH "/usr/share/easy-rsa"
 # path_prepend PATH "/build/os"
 
@@ -164,9 +148,9 @@ path_prepend PATH "${HOME}/bin"
 # https://firefox-source-docs.mozilla.org/setup/linux_build.html
 # ${HOME}/.local
 PYTHON_BASE="$(python3 -m site --user-base)"
-PYTHON_BASE_REFINED=$(echo "${PYTHON_BASE}" | sed 's#/#\\/#g' | \
-		sed 's#\.#\\.#g')
+PYTHON_BASE_REFINED="$(echo "${PYTHON_BASE}" | sed 's#/#\\/#g' | sed 's#\.#\\.#g')"
 path_prepend PATH "${PYTHON_BASE}/bin"
+[ ! -d "${PYTHON_BASE_REFINED}/bin" ] ||
 path_prepend PATH "${PYTHON_BASE_REFINED}/bin"
 path_prepend PATH "${HOME}/.local/bin"
 path_prepend PATH "${HOME}/.emacs.d/bin"
@@ -323,6 +307,26 @@ PURPLE='\e[1;35m'
   CYAN='\e[1;36m'
 	   NC='\e[0m'
 
+# if [ "$TERM" = "linux" ]; then
+#    echo -en "\e]P0232323" #black
+#    echo -en "\e]P82B2B2B" #darkgrey
+#    echo -en "\e]P1D75F5F" #darkred
+#    echo -en "\e]P9E33636" #red
+#    echo -en "\e]P287AF5F" #darkgreen
+#    echo -en "\e]PA98E34D" #green
+#    echo -en "\e]P3D7AF87" #brown
+#    echo -en "\e]PBFFD75F" #yellow
+#    echo -en "\e]P48787AF" #darkblue
+#    echo -en "\e]PC7373C9" #blue
+#    echo -en "\e]P5BD53A5" #darkmagenta
+#    echo -en "\e]PDD633B2" #magenta
+#    echo -en "\e]P65FAFAF" #darkcyan
+#    echo -en "\e]PE44C9C9" #cyan
+#    echo -en "\e]P7E5E5E5" #lightgrey
+#    echo -en "\e]PFFFFFFF" #white
+#    clear #for background artifacting
+# fi
+
 # Aliases
 alias cp='cp -iv'
 alias rcp='rsync -v --progress'
@@ -351,7 +355,9 @@ fi
 # alias grep='grep --colour=auto'
 # alias egrep='egrep --colour=auto'
 # alias ls='ls --color=auto --human-readable --group-directories-first --classify'
-alias ls='ls --color=auto -h --group-directories-first -F'
+[ -z "${IS_LINUX+x}" ] &&
+alias ls='ls --color=always -h -F' ||
+alias ls='ls --color=always -h --group-directories-first -F'
 
 # "parm_index" needs to be removed from terminfo -L1 screen-256color (look into "$SHARE_PREFIX/init/ashrc")
 # [ ! -z "${TMUX+x}" ] && {
@@ -362,18 +368,26 @@ alias ls='ls --color=auto -h --group-directories-first -F'
 #     alias ll='sh -c "ls --color=auto -h --group-directories-first -F -la;
 #     tmux copy-mode; tmux send-keys \#{pane_id} q"'
 # } ||
-alias ll='ls --color=auto -h --group-directories-first -F -la'
+[ -z "${IS_LINUX+x}" ] &&
+alias ll='ls --color=always -h -F -la' ||
+alias ll='ls --color=always -h --group-directories-first -F -la'
 
-alias la='ls --color=auto -h --group-directories-first -F -lathr'
+[ -z "${IS_LINUX+x}" ] &&
+alias la='ls --color=always -h -F -lathr' ||
+alias la='ls --color=always -h --group-directories-first -F -lathr'
 
-alias   nv='[ ! -f "$HOME/.vim/"*".tmp" ] || rm -f "$HOME/.vim*.tmp"; /usr/bin/nvim'
-alias nivm='[ ! -f "$HOME/.vim/"*".tmp" ] || rm -f "$HOME/.vim*.tmp"; /usr/bin/nvim'
-alias nvim='[ ! -f "$HOME/.vim/"*".tmp" ] || rm -f "$HOME/.vim*.tmp"; /usr/bin/nvim'
+_vim="$(which vim)"
+_nvim="$(which nvim)"
 
-if [ -e "/usr/bin/vim-huge" ]; then
-   alias vim='[ ! -f "$HOME/.vim/"*".tmp" ] || rm -f "$HOME/.vim*.tmp"; /usr/bin/vim-huge'
-elif [ -e "/usr/bin/vim" ]; then
-   alias vim='[ ! -f "$HOME/.vim/"*".tmp" ] || rm -f "$HOME/.vim*.tmp"; /usr/bin/vim'
+alias   nv="[ ! -f "$HOME/.vim/"*".tmp" ] || rm -f "$HOME/.vim*.tmp"; $_nvim"
+alias nivm="[ ! -f "$HOME/.vim/"*".tmp" ] || rm -f "$HOME/.vim*.tmp"; $_nvim"
+alias nvim="[ ! -f "$HOME/.vim/"*".tmp" ] || rm -f "$HOME/.vim*.tmp"; $_nvim"
+
+_vim_huge="$(which vim-huge 2> /dev/null || :)"
+if [ -e "$_vim_huge" ]; then
+   alias vim="[ ! -f "$HOME/.vim/"*".tmp" ] || rm -f "$HOME/.vim*.tmp"; $_vim_huge"
+elif [ -e "$_vim" ]; then
+   alias vim="[ ! -f "$HOME/.vim/"*".tmp" ] || rm -f "$HOME/.vim*.tmp"; $_vim"
 fi
 # This is nvi on current system. /usr/bin/vi is part of busybox
 # alias vi="/usr/bin/vi"
@@ -409,12 +423,16 @@ export QT_WAYLAND_FORCE_DPI=0
 export QT_AUTO_SCREEN_SCALE_FACTOR=0
 export QT_SCALE_FACTOR=1
 
-# GDK_SCALE allows only Integer values, GDK_DPI_SCALE=x allows decimal values such as . GDK_DPI_SCALE=0.66
-# export GDK_SCALE=0
-export GDK_SCALE=2.0
-export GDK_DPI_SCALE=2.0
-# export GDK_DPI_SCALE=0.75
-
+[ "$UID" -ne "0" ] && {
+	export GDK_SCALE=2.0
+	export GDK_DPI_SCALE=0.75
+} || {
+	# GDK_SCALE allows only Integer values, GDK_DPI_SCALE=x allows decimal values such as . GDK_DPI_SCALE=0.66
+	# export GDK_SCALE=0
+	export GDK_SCALE=2.0
+	export GDK_DPI_SCALE=2.0
+	# export GDK_DPI_SCALE=0.75
+}
 
 # https://forum.obarun.org/viewtopic.php?id=855
 [ "$DBUS_SESSION_ADDRESS" = "unix:path=$XDG_RUNTIME_DIR/bus" ] ||
@@ -479,29 +497,32 @@ export FONTCONFIG_PATH=/etc/fonts
 # ~/.vim/ftplugin/man.vim
 
 _busybox="$(which busybox)"
-[ -z "${_busybox:+x}" ] || { alias _vi='busybox vi'; alias vi='_vi'; }
-[ ! -z "${vi:+x}" ] || {
+[ -z "${_busybox:+x}" ] || {
+	# export _busybox;
+	alias vi="$_busybox vi"
+}
+[ ! -z "${_busybox:+x}" ] || {
 	_nvi="$(which nvi)"
-	[ -z "${_nvi:+x}" ] || alias vi='_nvi'
+	[ -z "${_nvi:+x}" ] || { export _nvi; alias vi="$_nvi"; }
 }
 
-_vim="$(which vim)"
-_nvim="$(which nvim)"
-
 [ ! -z "${manpager:+x}" ] ||
-! command -v "$vi"  > /dev/null 2>&1 || MANPAGER="vi"
+! command -v vi  > /dev/null 2>&1      || export manpager="vi"
 [ ! -z "${manpager:+x}" ] ||
-! command -v "$_vim"  > /dev/null 2>&1 || MANPAGER="vim"
+! command -v "$_vim"  > /dev/null 2>&1 || export manpager="vim"
 # neovim is not stable and light-weight
 [ ! -z "${manpager:+x}" ] ||
-! command -v "$_nvim" > /dev/null 2>&1 || MANPAGER="nvim"
-case "$MANPAGER" in
-	vim|nvim)
+! command -v "$_nvim" > /dev/null 2>&1 || export manpager="nvim"
+case "$manpager" in
+	# "vim")
+	#   export MANPAGER="/bin/sh -c \"col -b | vim -c 'set ft=man ts=4 nomod nolist nonu noma' -\""
+	#   ;;
+	"vim"|"nvim")
 		# export MANPAGER='/usr/bin/nvim --clean +Man!'
 		# export MANPAGER='/usr/bin/vim +Man!'
 		#
 		#     # Unterminated quoted string
-		#     # export MANPAGER="/bin/sh -c \"unset MANPAGER; col -b | vim -c 'set ft=man ts=4 nomod nolist nonu' -\""
+		#     # export MANPAGER="/bin/sh -c \"unset MANPAGER; col -b | vim -c 'set ft=man ts=4 nomod nolist nonu noma' -\""
 
 		# man: SYSERR: exec: : No such file or directory
 		#     export MANPAGER=$'
@@ -518,9 +539,9 @@ case "$MANPAGER" in
 		# -c \'+Man! $*\'
 		# "
 		# '
-		# Works
+		# Works for nvim
 		man() {
-			unset MANPAGER
+			# unset MANPAGER
 			col -b -x | \
 				"$manpager" --clean \
 				-c 'filetype plugin on' \
@@ -531,7 +552,8 @@ case "$MANPAGER" in
 				-c 'nnoremap u <c-u>' \
 				-c 'nnoremap <c-u> u' \
 				-c 'nnoremap K :Man <c-r>=expand(\\\"<cword>\\\")<cr><cr>' \
-				-c "Man $*"
+				-c "+Man! $*"
+				# -c "Man $*"
 			}
 		esac
 
diff --git a/init/etc/profile.d/share b/init/etc/profile.d/share
--- a/init/etc/profile.d/share
+++ b/init/etc/profile.d/share
@@ -40,46 +40,65 @@
 #
 # echo "FLAG: $FLAG, SHARE_PREFIX: $SHARE_PREFIX, HOME: $HOME, OPTION: $OPTION"
 # printf '%s\n' "$@"
+#
+# Set default path (/usr/sbin:/sbin:/bin included for non-KISS Linux chroots).
+export PATH=/usr/local/sbin:/usr/local/bin:/usr/bin:/usr/sbin:/sbin:/bin
 
-alias /='eval'
-# bash does not recognize //
-alias //='lineno="$LINENO"'
+# Set default umask.
+umask 022
 
 SCRIPT_NAME="share" && export SCRIPT_NAME
 
-# share folder initialization
-[ ! -z "${SHARE_PREFIX:+x}" ] || {
-	[ -d "/mnt/init" ] &&
-	{ SHARE_PREFIX="/mnt" && export SHARE_PREFIX; } || {
-		[ -d "/opt/init" ] &&
-		{ SHARE_PREFIX="/opt" && export SHARE_PREFIX; } ||
-		printf '%s %s\n' '$SHARE_PREFIX' "not found"
-	}
+[ ! -z "$(type "env_reset" > /dev/null && type "env_reset")" ] ||
+{
+	[ -f "/mnt/init/include/route" ] &&
+	. /mnt/init/include/route
+} || {
+	printf '%s %s\n' '$env_reset' "'$env_reset' could not get defined"
+	exit 0
 }
 
-_functions="$SHARE_PREFIX/init/functions"
-[ ! -f "$_functions" ] && {
-	printf '%s %s\n' '$_functions' "'$_functions' does not exist"
-	exit 0
-} || {
-	env_reset_type="$(type "env_reset" > /dev/null 2>&1 && type "env_reset")" || :
-	[ ! -z "${env_reset_type:+x}" ] ||
-		. "$_functions"
-}
+# alias /='eval'
+# # bash does not recognize //
+# alias //='lineno="$LINENO"'
+#
+# SCRIPT_NAME="share" && export SCRIPT_NAME
+#
+# # share folder initialization
+# [ ! -z "${SHARE_PREFIX:+x}" ] || {
+#   [ -d "/mnt/init" ] &&
+#   { SHARE_PREFIX="/mnt" && export SHARE_PREFIX; } || {
+#       [ -d "/opt/init" ] &&
+#       { SHARE_PREFIX="/opt" && export SHARE_PREFIX; } ||
+#       printf '%s %s\n' '$SHARE_PREFIX' "not found"
+#   }
+# }
+#
+# _functions="/usr/include/kiss/functions"
+# [ -f "$_functions" ] ||
+# _functions="$SHARE_PREFIX/init/include/functions"
+# [ ! -f "$_functions" ] && {
+#   printf '%s %s\n' '$_functions' "'$_functions' does not exist"
+#   exit 0
+# } || {
+#   env_reset_type="$(type "env_reset" > /dev/null 2>&1 && type "env_reset")" || :
+#   [ ! -z "${env_reset_type:+x}" ] ||
+#       . "$_functions"
+# }
 
 // env_reset UID "$(id -u)"
 
 # found_share_prefix=1
 # git_executable="$(which git)"
 # for item in $("$git_executable" config --system -l |
-# 	awk -F = "{print \$2}" 2> /dev/null); do
-# 	[ "$item" = "$SHARE_PREFIX" ] || continue
-# 	break
-# 	found_share_prefix=0
+#   awk -F = "{print \$2}" 2> /dev/null); do
+#   [ "$item" = "$SHARE_PREFIX" ] || continue
+#   break
+#   found_share_prefix=0
 # done
 #
 # [ "$found_share_prefix" = "0" ] ||
-# 	"$git_executable" config --system --add safe.directory "$SHARE_PREFIX"
+#   "$git_executable" config --system --add safe.directory "$SHARE_PREFIX"
 
 #
 # Made in /etc/profile
@@ -365,8 +384,9 @@ init_file_overwrite() {
 			return 0
 		} || {
 			[ -s "$target_dir/$file_name_source" ] &&
-			diff "$target_dir/$file_name_source" "$source" > /dev/null 2>&1 ||
-			/bin/cp -f "$source" "$target_dir/"
+			diff -bwrB "$target_dir/$file_name_source" "$source" > /dev/null 2>&1 ||
+			/bin/cp "$source" "$target_dir/"
+			# $(which rsync) -aq "$source" "$target_dir/"
 			return 0
 		}
 	}
@@ -377,13 +397,16 @@ init_file_overwrite() {
 
 	# local file_name_target="${target##*/}"
 	#
-	# diff "/etc/profile" "$SHARE_PREFIX/init/etc/profile" 2> /dev/null ||
-	#   \cp -f "$SHARE_PREFIX/init/etc/profile" "/etc/profile"
+	# diff -bwrB "/etc/profile" "$SHARE_PREFIX/init/etc/profile" 2> /dev/null ||
+	#   \cp "$SHARE_PREFIX/init/etc/profile" "/etc/profile"
 	[ ! -h "$target" ] || [ ! -L "$target" ] || \rm -f "$target"
 	[ -s "$target" ] &&
-	diff "$target" "$source" > /dev/null 2>&1 ||
-		/bin/cp -f "$source" "$target"
-		# /usr/bin/rsync -aq "$source" "$target"
+	diff -bwrB "$target" "$source" > /dev/null 2>&1 ||
+		# Don't force, it might reverse overwriting
+		# /bin/cp -f "$source" "$target"
+		/bin/cp "$source" "$target"
+		# On FreeBSD it is /usr/local/bin/rsync
+		# $(which rsync) -aq "$source" "$target"
 	[ -s "$target" ] || {
 		prompt '$lineno' "$lineno"
 		prompt '$target' "$target"
@@ -453,53 +476,56 @@ case "${id-} ${os_name-} ${os_pretty_name-}" in *"kiss"*)
 	# // init_file_overwrite "/etc/" "$SHARE_PREFIX/init/etc/inittab"
 esac
 
-[ "$UID" != "0" ] ||
 case "${id-} ${os_name-} ${os_pretty_name-}" in *"kiss"*|*"void"*|*"alpine"*)
-	# [ "$(cat /etc/hostname 2> /dev/null)" != "kiss" ] || {
-	# diff "/etc/profile" "$SHARE_PREFIX/init/etc/profile" 2> /dev/null ||
-	#   \cp -f "$SHARE_PREFIX/init/etc/profile" "/etc/profile"
-	// init_file_overwrite "/etc/profile" "$SHARE_PREFIX/init/etc/profile"
-	# // link_correct "$SHARE_PREFIX/init/etc/profile"                    "/etc/"
+	IS_LINUX= && export IS_LINUX
+	[ "$UID" != "0" ] || {
+		# [ "$(cat /etc/hostname 2> /dev/null)" != "kiss" ] || {
+		# diff -bwrB "/etc/profile" "$SHARE_PREFIX/init/etc/profile" 2> /dev/null ||
+		#   \cp -f "$SHARE_PREFIX/init/etc/profile" "/etc/profile"
+		// init_file_overwrite "/etc/profile" "$SHARE_PREFIX/init/etc/profile"
+		# // link_correct "$SHARE_PREFIX/init/etc/profile"                    "/etc/"
 
-	// init_file_overwrite "/etc/profile.d/kiss-env.sh" "$SHARE_PREFIX/init/etc/profile.d/kiss-env"
+		// init_file_overwrite "/etc/profile.d/kiss-env.sh" "$SHARE_PREFIX/init/etc/profile.d/kiss-env"
 
-	# // link_correct "$SHARE_PREFIX/init/etc/profile.d/nouveau"      "/etc/profile.d/nouveau.sh"
-	// init_file_overwrite "/etc/profile.d/nouveau.sh" "$SHARE_PREFIX/init/etc/profile.d/nouveau"
+		# // link_correct "$SHARE_PREFIX/init/etc/profile.d/nouveau"      "/etc/profile.d/nouveau.sh"
+		// init_file_overwrite "/etc/profile.d/nouveau.sh" "$SHARE_PREFIX/init/etc/profile.d/nouveau"
 
-	# // link_correct "$SHARE_PREFIX/init/etc/profile.d/iwl"          "/etc/profile.d/iwl.sh"
-	// init_file_overwrite "/etc/profile.d/iwl.sh" "$SHARE_PREFIX/init/etc/profile.d/iwl"
-	// init_file_overwrite "/etc/profile.d/eth.sh" "$SHARE_PREFIX/init/etc/profile.d/eth"
-	// init_file_overwrite "/usr/bin/s" "$SHARE_PREFIX/init/bin/s"
+		# // link_correct "$SHARE_PREFIX/init/etc/profile.d/iwl"          "/etc/profile.d/iwl.sh"
+		// init_file_overwrite "/etc/profile.d/iwl.sh" "$SHARE_PREFIX/init/etc/profile.d/iwl"
+		// init_file_overwrite "/etc/profile.d/eth.sh" "$SHARE_PREFIX/init/etc/profile.d/eth"
+		// init_file_overwrite "/usr/bin/s" "$SHARE_PREFIX/init/bin/s"
 
-	# [ ! -z "${IS_KISS+x}" ] || {
+		# [ ! -z "${IS_KISS+x}" ] || {
 
-	{ [ -h "$REPO_ROOT" ] || [ -L "$REPO_ROOT" ]; } && \rm -f "$REPO_ROOT"
-	[ -d "$REPO_ROOT" ] || \mkdir -p "$REPO_ROOT"
+		{ [ -h "$REPO_ROOT" ] || [ -L "$REPO_ROOT" ]; } && \rm -f "$REPO_ROOT"
+		[ -d "$REPO_ROOT" ] || \mkdir -p "$REPO_ROOT"
 
-	[ ! -e "$REPO_ROOT_DEV/choices" ] ||
-	// link_correct "$REPO_ROOT_DEV/choices" "$REPO_ROOT/"
-	[ ! -e "$REPO_ROOT_DEV/hooks" ] ||
-	// link_correct "$REPO_ROOT_DEV/hooks"   "$REPO_ROOT/"
+		[ ! -e "$REPO_ROOT_DEV/choices" ] ||
+		// link_correct "$REPO_ROOT_DEV/choices" "$REPO_ROOT/"
+		[ ! -e "$REPO_ROOT_DEV/hooks" ] ||
+		// link_correct "$REPO_ROOT_DEV/hooks"   "$REPO_ROOT/"
 
-	# }
+		# }
 
-	// link_correct "$SHARE_PREFIX/init/etc/grub.d/10_linux"          "/etc/grub.d/"
-	// link_correct "$SHARE_PREFIX/init/etc/modprobe.d/iwldvm.conf"   "/etc/modprobe.d/"
-	// link_correct "$SHARE_PREFIX/init/etc/modprobe.d/iwlmvm.conf"   "/etc/modprobe.d/"
-	// link_correct "$SHARE_PREFIX/init/etc/modprobe.d/iwlwifi.conf"  "/etc/modprobe.d/"
-	[ ! -e  "$MNGR_ROOT/usr/bin" ] ||
-	for item in $(\ls -1 "$MNGR_ROOT/usr/bin" | grep kiss); do
-		// link_correct "$MNGR_ROOT/usr/bin/$item" "/usr/bin/"
-	done
-	[ ! -e  "$MNGR_ROOT/usr/include" ] ||
-	for item in $(\ls -1 "$MNGR_ROOT/usr/include" | grep kiss); do
-		// link_correct "$MNGR_ROOT/usr/include/$item" "/usr/include/"
-	done
-	;;
-	*)
-	// init_file_overwrite "/etc/profile.d/functions.sh" "$SHARE_PREFIX/init/functions"
-
+		// link_correct "$SHARE_PREFIX/init/etc/grub.d/10_linux"          "/etc/grub.d/"
+		// link_correct "$SHARE_PREFIX/init/etc/modprobe.d/iwldvm.conf"   "/etc/modprobe.d/"
+		// link_correct "$SHARE_PREFIX/init/etc/modprobe.d/iwlmvm.conf"   "/etc/modprobe.d/"
+		// link_correct "$SHARE_PREFIX/init/etc/modprobe.d/iwlwifi.conf"  "/etc/modprobe.d/"
+		[ ! -e  "$MNGR_ROOT/usr/bin" ] ||
+		for item in $(\ls -1 "$MNGR_ROOT/usr/bin" | grep kiss); do
+			// link_correct "$MNGR_ROOT/usr/bin/$item" "/usr/bin/"
+		done
+		[ ! -e  "$MNGR_ROOT/usr/include" ] ||
+		for item in $(\ls -1 "$MNGR_ROOT/usr/include/kiss"); do
+			// link_correct "$MNGR_ROOT/usr/include/kiss/$item" "/usr/include/kiss/"
+		done
+	}
 esac
+
+[ "$UID" != "0" ] ||
+	// init_file_overwrite "/etc/profile.d/functions.sh" "$MNGR_ROOT/usr/include/functions"
+
+// init_file_overwrite "$SHARE_PREFIX/init/include/functions" "$MNGR_ROOT/usr/include/kiss/functions"
 
 insert_or_link() {
 	local source="$1"
@@ -519,10 +545,10 @@ export WAYLAND_CONFIG_HOME
 // link_correct "$SHARE_PREFIX/init/wayland/env" "${WAYLAND_CONFIG_HOME}/"
 
 # [ -f "$HOME/.profile" ] && {
-# 	diff -bwurB "$HOME/.profile" "$SHARE_PREFIX/init/profile" > /dev/null 2>&1 ||
-# 	grep -q '$SHARE_PREFIX/init/profile' ||
-# 	printf '\n%s\n%s\n' '[ ! -f "$SHARE_PREFIX/init/profile" ] ||' \
-# 	'. "$SHARE_PREFIX/init/profile"' >> "$HOME/.profile"
+#   diff -bwurB "$HOME/.profile" "$SHARE_PREFIX/init/profile" > /dev/null 2>&1 ||
+#   grep -q '$SHARE_PREFIX/init/profile' ||
+#   printf '\n%s\n%s\n' '[ ! -f "$SHARE_PREFIX/init/profile" ] ||' \
+#   '. "$SHARE_PREFIX/init/profile"' >> "$HOME/.profile"
 # } ||
 # // link_correct "$SHARE_PREFIX/init/profile" "$HOME/.profile"
 // insert_or_link "$SHARE_PREFIX/init/profile" "$HOME/.profile"
diff --git a/init/sway-launch b/init/sway-launch
--- a/init/sway-launch
+++ b/init/sway-launch
@@ -3,52 +3,61 @@ set -a
 
 printf '%s %s\n' '$tty_num' "$tty_num [enter sway-launch]"
 
-delegate() {
-	[ "$1" != "--" ] || shift 1
-	local value=
-	# "$@" won't lose any empty arguments
-	value="$("$@")" || { printf '\n'; exit 1; }
-	# "$@" | tail -n 1
-	# "$@" | awk 'END{print}'
+SCRIPT_NAME="sway-launch" && export SCRIPT_NAME
 
-	# Works
-	# "$@" | awk 'BEGIN { RS = '\n' } END { print }'
-	# printf '%s\n' "$value" | awk 'BEGIN { RS = '\n' } END { print }'
-	printf '%s\n' "$(awk 'BEGIN { RS = "\n" } END { print; print "\n" }' << EOF || :
-$value
-EOF
-)"
+[ ! -z "$(type "env_reset" > /dev/null && type "env_reset")" ] ||
+{
+	[ -f "/mnt/init/include/route" ] &&
+	. /mnt/init/include/route
+} || {
+	printf '%s %s\n' '$env_reset' "'$env_reset' could not get defined"
+	exit 0
 }
 
-sway_socket() {
-	local launcher="$1"
-	printf '%s %s\n' '$launcher' "$launcher"
-	# sock_id_list="$(ps -ef | grep "sway -d" | grep -v grep | \
-	#   grep -v swc-launch | sort -rnk3 | awk "{print \$1}" | tr -d " ")"
-	# # local index=0
-	# for sock_id in $sock_id_list; do
-	#    break
-	# done
+# alias /='eval'
+# # bash does not recognize //
+# alias //='lineno="$LINENO"'
+#
+# SCRIPT_NAME="sway-launch" && export SCRIPT_NAME
+#
+# # share folder initialization
+# [ ! -z "${SHARE_PREFIX:+x}" ] || {
+#   [ -d "/mnt/init" ] &&
+#   { SHARE_PREFIX="/mnt" && export SHARE_PREFIX; } || {
+#       [ -d "/opt/init" ] &&
+#       { SHARE_PREFIX="/opt" && export SHARE_PREFIX; } ||
+#       printf '%s %s\n' '$SHARE_PREFIX' "not found"
+#   }
+# }
+#
+# _functions="/usr/include/kiss/functions"
+# [ -f "$_functions" ] ||
+# _functions="$SHARE_PREFIX/init/include/functions"
+# [ ! -f "$_functions" ] && {
+#   printf '%s %s\n' '$_functions' "'$_functions' does not exist"
+#   exit 0
+# } || {
+#   env_reset_type="$(type "env_reset" > /dev/null && type "env_reset")" || :
+#   [ ! -z "${env_reset_type:+x}" ] ||
+#       . "$_functions"
+# }
 
-	sock_id="$(for item in $(
-	ps -ef | grep "sway -d" | grep -v "grep" | awk "{print \$2}" 2> /dev/null)
-	do
-		[ -z "$(pstree -p "$item" | grep "$item" | grep "sway" 2> /dev/null)" ] &&
-		continue || { printf '%s' "$item"; break; }
-	done)"
-
-	[ -n "${sock_id:+x}" ] || { printf '\n'; return 0; }
-
-	SWAY_SOCK="$XDG_RUNTIME_DIR/sway-ipc.$UID.$sock_id.sock"
-	[ ! -S "$SWAY_SOCK" ] || {
-		export SWAY_SOCK
-		[ -d "/tmp/wayland" ] || mkdir -p "/tmp/wayland"
-		printf '%s' "${SWAY_SOCK}" > /tmp/wayland/.socket
-
-		printf '%s %s\n' '$SWAY_SOCK' "$(cat "/tmp/wayland/.socket" 2> /dev/null)"
-	}
-	printf '\n%s' "$SWAY_SOCK"
-}
+# delegate() {
+#   [ "$1" != "--" ] || shift 1
+#   local value=
+#   # "$@" won't lose any empty arguments
+#   value="$("$@")" || { printf '\n'; exit 1; }
+#   # "$@" | tail -n 1
+#   # "$@" | awk 'END{print}'
+#
+#   # Works
+#   # "$@" | awk 'BEGIN { RS = '\n' } END { print }'
+#   # printf '%s\n' "$value" | awk 'BEGIN { RS = '\n' } END { print }'
+#   printf '%s\n' "$(awk 'BEGIN { RS = "\n" } END { print; print "\n" }' << EOF || :
+# $value
+# EOF
+# )"
+# }
 
 # https://www.reddit.com/r/voidlinux/comments/mor7n5/getting_libseat_errors_when_starting_sway/
 [ -n "${WAYLAND_CONFIG_HOME:+x}" ] ||
@@ -59,80 +68,107 @@ export WAYLAND_CONFIG_HOME
 # "${SHARE_PREFIX}/init/share" has the file structure
 # sway specific environment
 [ ! -f "${WAYLAND_CONFIG_HOME}/env" ] || {
+	printf '%s %s\n' "${WAYLAND_CONFIG_HOME}/env" "sourced"
 	set -a
 	# shellcheck disable=SC1090
 	. "${WAYLAND_CONFIG_HOME}/env"
 	set +a
 }
 
-# Reference implementation:
-# /usr/bin/sway -d > ${WAYLAND_CONFIG_HOME}/.autolauncher.log 2>&1
-# exec /usr/bin/sway -d > ${WAYLAND_CONFIG_HOME}/.autolauncher.log 2>&1
+insure_groups() {
+	has_group() { $(grep $1 /etc/group | awk -F : '{print $1}' | { while read -r line; do [ "$line" != "$1" ] || { return 0; }; done; return 1; }); return $?; }
 
-# swc-launch is used in preference to dbus
-launcher=$(which swc-launch 2> /dev/null || :)
-printf '%s %s\n' '$launcher' "$launcher [$LINENO]"
-{ [ ! -z "${launcher:+x}" ] ||
-command -v "$launcher" > /dev/null 2>&1; } && {
-	printf '%s %s\n' '$launcher' "$launcher [$LINENO]"
-	# exec swc-launch -t /dev/tty7 -- /usr/bin/sway -d > ${WAYLAND_CONFIG_HOME}/.autolauncher.log 2>&1 &
-	eval "nohup \"$launcher\" -t /dev/tty7 -- /usr/bin/sway -d \
-		> ${WAYLAND_CONFIG_HOME}/.autolauncher.log 2>&1 &"
-		# > ${WAYLAND_CONFIG_HOME}/.autolauncher.log && sway_socket "$launcher" 2>&1 &
-		sock_sway="$(delegate -- sway_socket "$launcher")"
-} || {
-	launcher=$(which dbus-run-session 2> /dev/null || :)
-	printf '%s %s\n' '$launcher' "$launcher [$LINENO]"
-	[ -z "${launcher:+x}" ] ||
-	command -v  "$launcher" > /dev/null 2>&1 && {
-		# https://github.com/microsoft/WSL/issues/7915
-		# doas killall dbus-daemon &&
-	
-		[ ! -z "$(id -u dbus 2> /dev/null)" ] || {
-			command -v  "/usr/bin/adduser" > /dev/null 2>&1 && {
-				doas addgroup -S dbus
-				doas adduser -S -H -G dbus dbus
-				[ ! -z "$(groups $USER | grep dbus)" ] || doas adduser -G dbus $USER
-			} ||
-			command -v  "/usr/bin/useradd" > /dev/null 2>&1 && {
-				doas groupadd -r dbus
-				doas useradd -r -M -G dbus dbus
-				[ ! -z "$(groups $USER | grep dbus)" ] || doas useradd -G dbus $USER
-			}
+	command -v  "/usr/bin/adduser" > /dev/null 2>&1 && {
+		# doas addgroup -S dbus
+		has_group $1 || doas adduser --user-group $1
+		# doas adduser -S -H -G dbus dbus
+		[ ! -z "$(id -u "$1" 2> /dev/null)" ] ||
+		doas adduser --system --no-create-home -g $1 $1
+		[ ! -z "$(groups $LOGNAME | grep $1)" ] || doas adduser -G $1 $LOGNAME
+	} || {
+		command -v  "/usr/bin/useradd" > /dev/null 2>&1 && {
+			has_group $1 || doas groupadd -r $1
+			# has_group dbus || doas groupadd -r dbus
+			# has_group _seatd || doas groupadd -r _seatd
+			# has_group _greeter || doas groupadd -r _greeter
+			[ ! -z "$(id -u "$1" 2> /dev/null)" ] ||
+			doas useradd -r -M -g $1 $1
+			# [ ! -z "$(id -u dbus 2> /dev/null)" ] ||
+			# doas useradd -r -M -g dbus dbus
+			# [ ! -z "$(id -u _seatd 2> /dev/null)" ] ||
+			# doas useradd -r -M -g _seatd _seatd
+			# [ ! -z "$(id -u _greeter 2> /dev/null)" ] ||
+			# doas useradd -r -M -g _greeter _greeter
+			#
+			# usermod -aG $1 "$LOGNAME"
+			# usermod -aG _seatd   "$LOGNAME"
+			# usermod -aG dbus     "$LOGNAME"
+			# usermod -aG _greeter "$LOGNAME"
+			[ ! -z "$(groups $LOGNAME | grep $1)" ] || doas useradd -G $1 $LOGNAME
+			# [ ! -z "$(groups $LOGNAME | grep dbus)" ] || doas useradd -G dbus $LOGNAME
+			# [ ! -z "$(groups $LOGNAME | grep _greeter)" ] || doas useradd -G _greeter $LOGNAME
+			# [ ! -z "$(groups $LOGNAME | grep _seatd)" ] || doas useradd -G _seatd $LOGNAME
 		}
-		doas -u dbus dbus-daemon --session --address=$DBUS_SESSION_BUS_ADDRESS \
-			--nofork --nopidfile --syslog-only &&
-	
-		# dbus-launch --sh-syntax --exit-with-session /usr/bin/sway -d > ${WAYLAND_CONFIG_HOME}/.autolauncher.log 2>&1
-		# exec will not give sock_sway opportunities to run
-		# exec  "$launcher" /usr/bin/sway -d \
-		eval "nohup \"$launcher\" /usr/bin/sway -d |
-			tee ${WAYLAND_CONFIG_HOME}/.autolauncher.log 2>&1 &"
+	}
+}
+
+[ ! -z "${sock_sway+x}" ] ||
+sock_sway=
+[ ! -z "${launcher+x}" ] ||
+launcher="greeter"
+
+[ -z "${DONT_USE_GREET=x}" ] && {
+	insure_groups "dbus"
+	insure_groups "_seatd"
+	# [ ! -z "${IS_KISS+x}" ] ||
+	insure_groups "_greeter"
+} || {
+	# Reference implementation:
+	# /usr/bin/sway -d > ${WAYLAND_CONFIG_HOME}/.autolauncher.log 2>&1
+	# exec /usr/bin/sway -d > ${WAYLAND_CONFIG_HOME}/.autolauncher.log 2>&1
+
+	# swc-launch is used in preference to dbus
+	launcher=$(which swc-launch 2> /dev/null || :)
+	printf '%s %s\n' '$launcher' "$launcher [$LINENO]"
+	{ [ ! -z "${launcher:+x}" ] ||
+	command -v "$launcher" > /dev/null 2>&1; } && {
+		printf '%s %s\n' '$launcher' "$launcher [$LINENO]"
+		# exec swc-launch -t /dev/tty7 -- /usr/bin/sway -d > ${WAYLAND_CONFIG_HOME}/.autolauncher.log 2>&1 &
+		eval "nohup \"$launcher\" -t /dev/tty7 -- /usr/bin/sway -d \
+			> ${WAYLAND_CONFIG_HOME}/.autolauncher.log 2>&1 &"
 			# > ${WAYLAND_CONFIG_HOME}/.autolauncher.log && sway_socket "$launcher" 2>&1 &
-		# nohup dbus-run-session /usr/bin/sway -d > ${WAYLAND_CONFIG_HOME}/.autolauncher.log 2>&1 &
-		sock_sway="$(delegate -- sway_socket "$launcher")"
+			sock_sway="$(delegate -- sway_socket "$launcher")"
+	} || {
+		launcher=$(which dbus-run-session 2> /dev/null || :)
+		printf '%s %s\n' '$launcher' "$launcher [$LINENO]"
+		[ -z "${launcher:+x}" ] ||
+		command -v  "$launcher" > /dev/null 2>&1 && {
+			# https://github.com/microsoft/WSL/issues/7915
+			# doas killall dbus-daemon &&
+			#
+			# https://docs.voidlinux.org/config/graphical-session/graphics-drivers/intel.html
+			# https://www.reddit.com/r/voidlinux/comments/mc24te/starting_sway_problem/
+			# dbus-elogind/elogind/pam_rundir/mesa-dri
+			# [ ! -z "$(id -u dbus 2> /dev/null)" ] || {
+			insure_groups "dbus"
+			insure_groups "_seatd"
+			# }
+			doas -u dbus dbus-daemon --session --address=$DBUS_SESSION_BUS_ADDRESS \
+				--nofork --nopidfile --syslog-only &&
+			# dbus-launch --sh-syntax --exit-with-session /usr/bin/sway -d > ${WAYLAND_CONFIG_HOME}/.autolauncher.log 2>&1
+			# exec will not give sock_sway opportunities to run
+			# exec  "$launcher" /usr/bin/sway -d \
+			eval "nohup \"$launcher\" /usr/bin/sway -d |
+				tee ${WAYLAND_CONFIG_HOME}/.autolauncher.log 2>&1 &"
+				# > ${WAYLAND_CONFIG_HOME}/.autolauncher.log && sway_socket "$launcher" 2>&1 &
+			# nohup dbus-run-session /usr/bin/sway -d > ${WAYLAND_CONFIG_HOME}/.autolauncher.log 2>&1 &
+			sock_sway="$(delegate -- sway_socket "$launcher")"
+		}
 	}
 }
 
 # [ -n "${sock_sway:+x}" ] || nohup river &
 
-[ -z "${WAYLAND_DISPLAY+x}" ] || {
-	printf '%s %s\n' '$SHLVL' "$SHLVL" >> ${WAYLAND_CONFIG_HOME}/.autolauncher.log 2>&1
-	printf '%s %s\n' '$WAYLAND_DISPLAY' "$WAYLAND_DISPLAY" >> ${WAYLAND_CONFIG_HOME}/.autolauncher.log 2>&1
-	export WAYLAND_DISPLAY
-	printf '%s' "${WAYLAND_DISPLAY}" > $HOME/.wayland_display
-	[ -d "/tmp/wayland" ] || \mkdir -p "/tmp/wayland"
-	printf '%s' "${WAYLAND_DISPLAY}" > /tmp/wayland/.display
-
-	sock_id="$(ps -ef | grep "sway -d" | grep -v grep | \
-		grep -v swc-launch | awk "{print \$1}" | tr -d " ")"
-	SWAY_SOCK="$XDG_RUNTIME_DIR/sway-ipc.$(id -u).$sock_id.sock"
-	[ ! -S "$SWAY_SOCK" ] || {
-		export SWAY_SOCK
-		printf '%s' "${WAYLAND_DISPLAY}" > /tmp/wayland/.socket
-	}
-
-	[ -z "${DISPLAY+x}" ] || unset DISPLAY
-	# DISPLAY=${WAYLAND_DISPLAY}
-	# export DISPLAY
-}
+[ -z "${WAYLAND_DISPLAY+x}" ] ||
+[ ! -z "${sock_sway:+x}" ] ||
+	sock_sway="$(delegate -- sway_socket "$launcher")"
