"expr" is not posix, removed

diff --git a/init/ashrc b/init/ashrc
--- a/init/ashrc
+++ b/init/ashrc
@@ -3,6 +3,19 @@
 # Definition sequence
 # doas.conf->share->/etc/profile->login shell->.profile->.ashrc->env
 
+# share folder initialization
+[ ! -z "${SHARE_PREFIX:+x}" ] || {
+	[ -d "/mnt/init" ] &&
+	{ SHARE_PREFIX="/mnt" && export SHARE_PREFIX; } || {
+		[ -d "/opt/init" ] &&
+		{ SHARE_PREFIX="/opt" && export SHARE_PREFIX; } ||
+		printf '%s %s\n' '$SHARE_PREFIX' "not found"
+	}
+}
+
+[ ! -f "$SHARE_PREFIX/init/functions" ] ||
+. "$SHARE_PREFIX/init/functions"
+
 # : ${UID="$(id -u)"} && export UID
 env_reset UID "$(id -u)"
 
@@ -370,19 +383,11 @@ reset_cursor_shape
 tabs -4
 LESS="-x4" && export LESS
 
-# share folder initialization
-[ ! -z "${SHARE_PREFIX:+x}" ] ||
-if [ -d "/mnt/init" ]; then
-	SHARE_PREFIX="/mnt"
-	export SHARE_PREFIX
-elif [ -d "/opt/init" ]; then
-	SHARE_PREFIX="/opt"
-	export SHARE_PREFIX
-fi
-
 [ ! -d "${SHARE_PREFIX}/init" ] || {
 	[ ! -f "${SHARE_PREFIX}/init/env" ] ||
 		. ${SHARE_PREFIX}/init/env
+
+	[ -z "${IS_KISS:+x}" ] ||
 	[ ! -f "${SHARE_PREFIX}/init/kiss-env" ] ||
 		. ${SHARE_PREFIX}/init/kiss-env
 }
@@ -769,8 +774,6 @@ else
 	)\[\033[m\]\[$(eval "$back_ground_user")\]\u@${HOSTNAME}:\[\033[m\]\[$(eval "$back_ground_user")\]\w \[\033[m\]\n'
 
 fi
-
-dmesg -n 1
 
 parent_is_tmux() {
 	local result=1
diff --git a/init/env b/init/env
--- a/init/env
+++ b/init/env
@@ -9,6 +9,19 @@ newline="
 alias /='eval'
 alias //='lineno="$LINENO"'
 
+# share folder initialization
+[ ! -z "${SHARE_PREFIX:+x}" ] || {
+	[ -d "/mnt/init" ] &&
+	{ SHARE_PREFIX="/mnt" && export SHARE_PREFIX; } || {
+		[ -d "/opt/init" ] &&
+		{ SHARE_PREFIX="/opt" && export SHARE_PREFIX; } ||
+		printf '%s %s\n' '$SHARE_PREFIX' "not found"
+	}
+}
+
+[ ! -f "$SHARE_PREFIX/init/functions" ] ||
+. "$SHARE_PREFIX/init/functions"
+
 env_reset "IFS" " $(printf '%s' "t" | tr 't' "\\t")${newline}"
 
 # env_reset() {
@@ -23,101 +36,7 @@ env_reset "IFS" " $(printf '%s' "t" | tr 't' "\\t")${newline}"
 # user="$(whoami)"
 # [ "$USER" = "$user" ] || USER="$user" && export USER
 env_reset USER "$(whoami)"
-# https://unix.stackexchange.com/questions/32041/checking-if-path-contains-home-mydir-and-adding-it-if-not-all-in-a-script
-# https://tldp.org/LDP/abs/html/parameter-substitution.html
-# "grep -q" "$? -eq 0" could be a good solution?
-prepend() {
-	[ ! -z "${1:+x}" ] || return
-	local key="${1}"
-	# CONTAINER_VALUE="$(eval echo "\$${1}")"
-	local value="${2}"
-	[ -d "${value}" ] || return
-	# echo "prepend \$key   = $key"
-	# echo "prepend \$CONTAINER_VALUE = $(eval echo "\$${key}")"
-	case ":$(eval echo "\$${key}"):" in
-		*":${value}:"*) :;;
-		*) eval "export $key=${value}\${$key:+\":\$$key\"}" ;;
-	esac
-}
-# prepend PATH "/build/os"
 
-# https://superuser.com/questions/39751/add-directory-to-path-if-its-not-already-there
-# # prepend to PATH
-# _path_prepend "$XDG_DATA_HOME/phpenv/bin"
-#
-# # prepend to MANPATH
-# _path_prepend MANPATH "$XDG_DATA_HOME/shell-installer/man"
-#
-# # prepend to PERL5LIB
-# _path_prepend PERL5LIB "$PERL_LOCAL_LIB_ROOT/lib/perl5"
-#
-# Features
-#
-#     POSIX compliant
-#     Doesn't use Bash's declare -n
-
-prepend_path() {
-	if [ -n "$2" ]; then
-		case ":$(eval "echo \${${1}-}"):" in
-			*":$2:"*) :;;
-			*) eval "export $1=$2\${$1:+\":\$$1\"}" ;;
-		esac
-	else
-		case ":$PATH:" in
-			*":$1:"*) :;;
-			*) export PATH="$1${PATH:+":$PATH"}" ;;
-		esac
-	fi
-}
-
-append_path() {
-	if [ -n "$2" ]; then
-		case ":$(eval "echo \${${1}-}"):" in
-			*":$2:"*) :;;
-			*) eval "export $1=\${$1:+\"\$$1:\"}$2" ;;
-		esac
-	else
-		case ":$PATH:" in
-			*":$1:"*) :;;
-			*) export PATH="${PATH:+"$PATH:"}$1" ;;
-		esac
-	fi
-}
-
-# https://unix.stackexchange.com/questions/4965/keep-duplicates-out-of-path-on-source
-# Define path_append and path_prepend to add directory to target path, e.g.
-# PATH, MANPATH
-# Add to the end of a target path
-_path_append() {
-	[ ! -z "${1:+x}" ] &&
-	[ -d "$2" ] || return
-	local extend=":$(eval "echo \${${1}-}"):"
-	# echo "\$2 = $2"
-	# echo "test=${extend##*:$2:*}"
-	# [ -d "$2" ] || {
-	# eval test -z "\"\${$1##*:$2:*}\"" -o -z "\"\${$1%%*:$2}\"" \
-	# -o -z "\"\${$1##$2:*}\"" -o -z "\"\${$1##$2}\"" ||
-	[ "$extend" = "::" ] && eval "export $1=$2" ||
-	[ -z "${extend##*:$2:*}" ] || eval "export $1=\$$1:$2"
-	# }
-}
-alias path_append='_path_append'
-
-# Add to the front of a target path
-_path_prepend() {
-	[ ! -z "${1:+x}" ] &&
-	[ -d "$2" ] || return
-	local extend=":$(eval "echo \${${1}-}"):"
-	# echo "\$2 = $2"
-	# echo "test=${extend##*:$2:*}"
-	# [ ! -d "$2" ] || {
-	# eval test -z "\"\${$1##*:$2:*}\"" -o -z "\"\${$1%%*:$2}\"" \
-	# -o -z "\"\${$1##$2:*}\"" -o -z "\"\${$1##$2}\"" ||
-	[ "$extend" = "::" ] && eval "export $1=$2" ||
-	[ -z "${extend##*:$2:*}" ] || eval "export $1=$2:\$$1"
-	# }
-}
-alias path_prepend='_path_prepend'
 path_prepend PATH "$SHARE_PREFIX/init"
 
 # echo "\$TERM = $TERM"
@@ -484,8 +403,8 @@ export QT_SCALE_FACTOR=1
 # GDK_SCALE allows only Integer values, GDK_DPI_SCALE=x allows decimal values such as . GDK_DPI_SCALE=0.66
 # export GDK_SCALE=0
 export GDK_SCALE=2.0
-# export GDK_DPI_SCALE=2.0
-export GDK_DPI_SCALE=0.75
+export GDK_DPI_SCALE=2.0
+# export GDK_DPI_SCALE=0.75
 
 
 # https://forum.obarun.org/viewtopic.php?id=855
@@ -550,46 +469,62 @@ export FONTCONFIG_PATH=/etc/fonts
 # https://muru.dev/2015/08/28/vim-for-man.html
 # ~/.vim/ftplugin/man.vim
 
-# neovim is not stable and light-weight
-# ! command -v /usr/bin/nvim > /dev/null 2>&1 || {
-! command -v /usr/bin/vim > /dev/null 2>&1 || {
-	# export MANPAGER='/usr/bin/nvim --clean +Man!'
-	# export MANPAGER='/usr/bin/vim +Man!'
-#
-#     # Unterminated quoted string
-#     # export MANPAGER="/bin/sh -c \"unset MANPAGER; col -b | vim -c 'set ft=man ts=4 nomod nolist nonu' -\""
-
-# man: SYSERR: exec: : No such file or directory
-#     export MANPAGER=$'
-#     /bin/sh -c "
-#     unset MANPAGER; col -b -x |
-# nvim -R
-# -c \'set ft=man ts=4 nomod nolist nonu\'
-# -c \'nnoremap q :q<cr>\'
-# -c \'nnoremap <space> <c-d>\'
-# -c \'nnoremap , <c-d>\'
-# -c \'nnoremap u <c-u>\'
-# -c \'nnoremap <c-u> u\'
-# -c \'nnoremap K :Man <c-r>=expand(\\\"<cword>\\\")<cr><cr>\'
-# -c \'+Man! $*\'
-# "
-# '
-	# Works
-	man() {
-		unset MANPAGER
-		col -b -x | \
-		vim --clean \
-			-c 'filetype plugin on' \
-			-c 'set ft=man ts=4 nomod nolist nonu' \
-			-c 'nnoremap q :q<cr>' \
-			-c 'nnoremap <space> <c-d>' \
-			-c 'nnoremap , <c-d>' \
-			-c 'nnoremap u <c-u>' \
-			-c 'nnoremap <c-u> u' \
-			-c 'nnoremap K :Man <c-r>=expand(\\\"<cword>\\\")<cr><cr>' \
-			-c "Man $*"
-	}
+_busybox="$(which busybox)"
+[ -z "${_busybox:+x}" ] || { alias _vi='busybox vi'; alias vi='_vi'; }
+[ ! -z "${vi:+x}" ] || {
+	_nvi="$(which nvi)"
+	[ -z "${_nvi:+x}" ] || alias vi='_nvi'
 }
+
+_vim="$(which vim)"
+_nvim="$(which nvim)"
+
+[ ! -z "${manpager:+x}" ] ||
+! command -v "$vi"  > /dev/null 2>&1 || MANPAGER="vi"
+[ ! -z "${manpager:+x}" ] ||
+! command -v "$_vim"  > /dev/null 2>&1 || MANPAGER="vim"
+# neovim is not stable and light-weight
+[ ! -z "${manpager:+x}" ] ||
+! command -v "$_nvim" > /dev/null 2>&1 || MANPAGER="nvim"
+case "$MANPAGER" in
+	vim|nvim)
+		# export MANPAGER='/usr/bin/nvim --clean +Man!'
+		# export MANPAGER='/usr/bin/vim +Man!'
+		#
+		#     # Unterminated quoted string
+		#     # export MANPAGER="/bin/sh -c \"unset MANPAGER; col -b | vim -c 'set ft=man ts=4 nomod nolist nonu' -\""
+
+		# man: SYSERR: exec: : No such file or directory
+		#     export MANPAGER=$'
+		#     /bin/sh -c "
+		#     unset MANPAGER; col -b -x |
+		# nvim -R
+		# -c \'set ft=man ts=4 nomod nolist nonu\'
+		# -c \'nnoremap q :q<cr>\'
+		# -c \'nnoremap <space> <c-d>\'
+		# -c \'nnoremap , <c-d>\'
+		# -c \'nnoremap u <c-u>\'
+		# -c \'nnoremap <c-u> u\'
+		# -c \'nnoremap K :Man <c-r>=expand(\\\"<cword>\\\")<cr><cr>\'
+		# -c \'+Man! $*\'
+		# "
+		# '
+		# Works
+		man() {
+			unset MANPAGER
+			col -b -x | \
+				"$manpager" --clean \
+				-c 'filetype plugin on' \
+				-c 'set ft=man ts=4 nomod nolist nonu' \
+				-c 'nnoremap q :q<cr>' \
+				-c 'nnoremap <space> <c-d>' \
+				-c 'nnoremap , <c-d>' \
+				-c 'nnoremap u <c-u>' \
+				-c 'nnoremap <c-u> u' \
+				-c 'nnoremap K :Man <c-r>=expand(\\\"<cword>\\\")<cr><cr>' \
+				-c "Man $*"
+			}
+		esac
 
 export MANWIDTH=999
 
diff --git a/init/etc/profile b/init/etc/profile
--- a/init/etc/profile
+++ b/init/etc/profile
@@ -11,16 +11,34 @@ export PATH=/usr/local/sbin:/usr/local/bin:/usr/bin:/usr/sbin:/sbin:/bin
 umask 022
 
 alias /='eval'
+alias //='lineno="$LINENO"'
 
-_env_reset() {
-	local env_key_name="${1:?"Must give a key"}"
-	local env_value="${2:?"Must give a value"}"
-	/ "[ \"\${$env_key_name-}\" = \"$env_value\" ]" || {
-		# / "echo \"Original \\$\$env_key_name = \${$env_key_name-}\""
-		/ "$env_key_name=\"$env_value\"" && / "export \"$env_key_name\""
+# share folder initialization
+[ ! -z "${SHARE_PREFIX:+x}" ] || {
+	[ -d "/mnt/init" ] &&
+	{ SHARE_PREFIX="/mnt" && export SHARE_PREFIX; } || {
+		[ -d "/opt/init" ] &&
+		{ SHARE_PREFIX="/opt" && export SHARE_PREFIX; } ||
+		printf '%s %s\n' '$SHARE_PREFIX' "not found"
 	}
 }
-alias env_reset='_env_reset'
+
+[ ! -f "$SHARE_PREFIX/init/functions" ] ||
+. "$SHARE_PREFIX/init/functions"
+
+case "$(type env_reset)" in *"function"*|*"alias"*) ;;
+	*)
+	_env_reset() {
+		local env_key_name="${1:?"env_reset needs a key"}"
+		local env_value="${2:?"env_reset needs a value"}"
+		/ "[ \"\${$env_key_name-}\" = \"$env_value\" ]" || {
+			# / "echo \"Original \\$\$env_key_name = \${$env_key_name-}\""
+			/ "$env_key_name=\"$env_value\"" && / "export \"$env_key_name\""
+		}
+	}
+	alias env_reset='_env_reset'
+esac
+
 env_reset os_name "$(cat /etc/hostname 2> /dev/null)"
 # : ${os_name:="$(cat /etc/hostname 2> /dev/null)"}
 # : ${os_name:="$(awk -F = '$1 == "ID" {print $2}' < /etc/os-release)"}
@@ -33,6 +51,7 @@ case "${os_name} ${os_pretty_name}" in *"kiss"*|*"KISS"*)
 	# trap '"${LINENO-}" "${FUNCNAME-}" "${0-}"' ERR || :
 esac
 
+env_reset UID "$(id -u)"
 # : "${LOGNAME:="$(/usr/bin/whoami)"}" && export LOGNAME
 env_reset LOGNAME "$(/usr/bin/whoami)"
 # [ -n "${LOGNAME+x}" ] || export LOGNAME="$(/usr/bin/whoami)"
@@ -48,18 +67,6 @@ env_reset HOME "$(/usr/bin/awk -F : -v v="${LOGNAME}" \
 #     echo "Fixed \$HOME = $HOME"
 # }
 
-# share folder initialization
-[ ! -z "${SHARE_PREFIX:+x}" ] ||
-if [ -d "/mnt/init" ]; then
-	SHARE_PREFIX="/mnt"
-	export SHARE_PREFIX
-elif [ -d "/opt/init" ]; then
-	SHARE_PREFIX="/opt"
-	export SHARE_PREFIX
-else
-	printf '%s %s\n' '$SHARE_PREFIX' "is not defined"
-fi
-
 env_reset LAYOUT_INIT "${SHARE_PREFIX}/init/etc/profile.d/share"
 
 [ ! -z "${loaded_share+x}" ] ||
@@ -68,37 +75,29 @@ env_reset LAYOUT_INIT "${SHARE_PREFIX}/init/etc/profile.d/share"
 	. "$LAYOUT_INIT"
 }
 
-# How do I tell I'm runing in a chroot?
-# https://unix.stackexchange.com/questions/14345/how-do-i-tell-im-running-in-a-chroot
-
-# No root needed. Equal means not in a chroot
-# [ "$(awk '$5=="/" {print $1}' </proc/1/mountinfo)" != "$(awk '$5=="/" {print $1}' </proc/$$/mountinfo)" ]
-# root permission needed
-# if [ "$(stat -c %d:%i /)" != "$(stat -c %d:%i /proc/1/root/.)" ]; then
-#     echo "We are chrooted!"
-# else
-#     echo "Business as usual"
-# fi
-
 # Try to tell I'm runing in a chroot. Equal means not in a chroot
 # Not equal (contains) means in a chroot, then ignore the tmux application, etc.
-is_chrooted() {
-	local being_in_chroot=0
-	local root_pid="$(awk '$5 == "/" {print $1}' < /proc/1/mountinfo)"
-	local pid_list="$(awk '$5 == "/" {print $1}' < /proc/$$/mountinfo)"
-	local is_pid_contained=1
+case "$(type is_chrooted)" in *"function"*|*"alias"*) ;;
+	*)
+		_is_chrooted() {
+			local being_in_chroot=0
+			local root_pid="$(awk '$5 == "/" {print $1}' < /proc/1/mountinfo)"
+			local pid_list="$(awk '$5 == "/" {print $1}' < /proc/$$/mountinfo)"
+			local is_pid_contained=1
 
-	case " $pid_list " in
-		*" $root_pid "*) is_pid_contained=0
-	esac
+			case " $pid_list " in
+				*" $root_pid "*) is_pid_contained=0
+			esac
 
-	[ ! -f "/proc/1/mountinfo" ] ||
-	[ ! -f "/proc/$$/mountinfo" ] ||
-	[ "$is_pid_contained" -ne "0" ] ||
-	being_in_chroot=1
+			[ ! -f "/proc/1/mountinfo" ] ||
+				[ ! -f "/proc/$$/mountinfo" ] ||
+				[ "$is_pid_contained" -ne "0" ] ||
+				being_in_chroot=1
 
-	return $being_in_chroot
-}
+			return $being_in_chroot
+		}
+	alias is_chrooted='_is_chrooted'
+esac
 
 # Load profiles from /etc/profile.d
 is_chrooted && {
@@ -118,6 +117,11 @@ for file in /etc/profile.d/*.sh; do
 	# } ||
 	. "$file"
 done
+
+[ "$UID" != "0" ] || dmesg -n 1
+# ! command -v "/usr/bin/doas" > /dev/null 2>&1 ||
+# doas dmesg -n 1
+
 # setterm -initialize
 # echo 5 | doas tee /sys/module/vt/parameters/cur_default
 unset file
diff --git a/init/etc/profile.d/kiss-env b/init/etc/profile.d/kiss-env
--- a/init/etc/profile.d/kiss-env
+++ b/init/etc/profile.d/kiss-env
@@ -2,19 +2,20 @@
 # Initialize the environment variables/flags/repositories
 
 alias /='eval'
+alias //='lineno="$LINENO"'
 
-case "$(type env_reset)" in
-	*"function"*) ;;
-	*)
-		env_reset() {
-			local env_key_name="${1:?"Must give a key"}"
-			local env_value="${2:?"Must give a value"}"
-			/ "[ \"\${$env_key_name-}\" = \"$env_value\" ]" || {
-				# / "echo \"Original \\$\$env_key_name = \${$env_key_name-}\""
-				/ "$env_key_name=\"$env_value\"" && / "export \"$env_key_name\""
-			}
-		}
-esac
+# share folder initialization
+[ ! -z "${SHARE_PREFIX:+x}" ] || {
+	[ -d "/mnt/init" ] &&
+	{ SHARE_PREFIX="/mnt" && export SHARE_PREFIX; } || {
+		[ -d "/opt/init" ] &&
+		{ SHARE_PREFIX="/opt" && export SHARE_PREFIX; } ||
+		printf '%s %s\n' '$SHARE_PREFIX' "not found"
+	}
+}
+
+[ ! -f "$SHARE_PREFIX/init/functions" ] ||
+. "$SHARE_PREFIX/init/functions"
 
 # : "${LOGNAME:="$(/usr/bin/whoami)"}" && export LOGNAME
 env_reset LOGNAME "$(/usr/bin/whoami)"
diff --git a/init/etc/profile.d/share b/init/etc/profile.d/share
--- a/init/etc/profile.d/share
+++ b/init/etc/profile.d/share
@@ -45,26 +45,20 @@ alias /='eval'
 # bash does not recognize //
 alias //='lineno="$LINENO"'
 
-case "$(type env_reset)" in *"function"*|*"alias"*) ;;
-	*)
-	_env_reset() {
-		local env_key_name="${1:?"env_reset needs a key"}"
-		local env_value="${2:?"env_reset needs a value"}"
-		/ "[ \"\${$env_key_name-}\" = \"$env_value\" ]" || {
-			# / "echo \"Original \\$\$env_key_name = \${$env_key_name-}\""
-			/ "$env_key_name=\"$env_value\"" && / "export \"$env_key_name\""
-		}
+# share folder initialization
+[ ! -z "${SHARE_PREFIX:+x}" ] || {
+	[ -d "/mnt/init" ] &&
+	{ SHARE_PREFIX="/mnt" && export SHARE_PREFIX; } || {
+		[ -d "/opt/init" ] &&
+		{ SHARE_PREFIX="/opt" && export SHARE_PREFIX; } ||
+		printf '%s %s\n' '$SHARE_PREFIX' "not found"
 	}
-	alias env_reset='_env_reset'
-esac
-
-
-[ ! -z "${SHARE_PREFIX:+x}" ] || [ ! -d "/mnt/init" ] || {
-	SHARE_PREFIX="/mnt" && export SHARE_PREFIX
 }
-[ ! -z "${SHARE_PREFIX:+x}" ] || [ ! -d "/opt/init" ] || {
-	SHARE_PREFIX="/opt" && export SHARE_PREFIX
-}
+
+[ ! -f "$SHARE_PREFIX/init/functions" ] ||
+. "$SHARE_PREFIX/init/functions"
+
+env_reset UID "$(id -u)"
 
 # found_share_prefix=1
 # git_executable="$(which git)"
@@ -118,7 +112,8 @@ link_correct() {
 		return 0
 	}
 	# [ "${target:$((${#target}-1)):1}" = '/' ] && target="${target%/}"
-	[ "$(expr substr "$target" "$(expr length "$target")" 1)" != '/' ] ||
+	# [ "$(expr substr "$target" "$(expr length "$target")" 1)" != '/' ] ||
+	[ "$(awk -- "BEGIN { print substr (ARGV[1], "${#target}", 1) }" "$target")" != '/' ] ||
 		target="${target%/}"
 	[ ! -z "${target:+x}" ] || {
 		prompt '$target' "'$target' is root mount point"
@@ -133,7 +128,8 @@ link_correct() {
 	}
 	local anchor="$2"
 	local anchor_name="${anchor##*/}"
-	[ "$(expr substr "$anchor" "$(expr length "$anchor")" 1)" != '/' ] ||
+	# [ "$(expr substr "$anchor" "$(expr length "$anchor")" 1)" != '/' ] ||
+	[ "$(awk -- "BEGIN { print substr (ARGV[1], "${#anchor}", 1) }" "$anchor")" != '/' ] ||
 		anchor_name="$target_name"
 
 	[ -n "${anchor:+x}" ] || {
@@ -236,7 +232,8 @@ link_correct() {
 
 	local anchor_dir=
 	# "$anchor" does not exist yet
-	[ "$(expr substr "$anchor" "$(expr length "$anchor")" 1)" != '/' ] && {
+	# [ "$(expr substr "$anchor" "$(expr length "$anchor")" 1)" != '/' ] && {
+	[ "$(awk -- "BEGIN { print substr (ARGV[1], "${#anchor}", 1) }" "$anchor")" != '/' ] && {
 		[ "${anchor##*/}" != "$target_name" ] && {
 			# $REPO_ROOT_DEV/usr/bin/kiss <- /usr/bin
 			[ -d "$anchor" ] && {
@@ -365,7 +362,8 @@ init_file_overwrite() {
 		}
 	}
 
-	[ "$(expr substr "$target" "$(expr length "$target")" 1)" != '/' ] ||
+	# [ "$(expr substr "$target" "$(expr length "$target")" 1)" != '/' ] ||
+	[ "$(awk -- "BEGIN { print substr (ARGV[1], "${#target}", 1) }" "$target")" != '/' ] ||
 	target="${target%/}"
 
 	# local file_name_target="${target##*/}"
@@ -389,6 +387,7 @@ init_file_overwrite() {
 	return 0
 }
 
+[ "$UID" != "0" ] ||
 # // link_correct "${SHARE_PREFIX}/init/etc/profile.d/share" "/etc/profile.d/share.sh"
 # // init_file_overwrite "/etc/profile.d/share.sh" "${SHARE_PREFIX}/init/etc/profile.d/share"
 // init_file_overwrite "/etc/profile.d/xdg-runtime-dir.sh" \
@@ -442,6 +441,7 @@ case "${os_name} ${os_pretty_name}" in *"kiss"*|*"KISS"*)
 	# // init_file_overwrite "/etc/" "${SHARE_PREFIX}/init/etc/inittab"
 esac
 
+[ "$UID" != "0" ] ||
 case "${os_name} ${os_pretty_name}" in *"kiss"*|*"KISS"*|*"void"*|*"Void"*|*"alpine"*|*"Alpine"*)
 	# [ "$(cat /etc/hostname 2> /dev/null)" != "kiss" ] || {
 	# diff "/etc/profile" "${SHARE_PREFIX}/init/etc/profile" 2> /dev/null ||
