Use Escape as Tmux prefix

diff --git a/init/etc/profile.d/kiss-env b/init/etc/profile.d/kiss-env
--- a/init/etc/profile.d/kiss-env
+++ b/init/etc/profile.d/kiss-env
@@ -3,6 +3,8 @@
 
 alias /='eval'
 alias //='lineno="$LINENO"'
+newline="
+"
 
 SCRIPT_NAME="kiss-env" && export SCRIPT_NAME
 
@@ -40,130 +42,76 @@ SCRIPT_NAME="kiss-env" && export SCRIPT_NAME
 #       . "$_functions"
 # }
 
+# kiss_root         : "$1"
+# kiss_repo_local   : "$2"
+# repo_root         : "$3"
+# repo_main_source  : "$4"
+repo_main() {
+
+	# local kiss_repo_name="$1"
+	# shift 1
+	# local kiss_root="${1:?"Fake root can not be empty"}"
+	# Empty means the local host
+	local kiss_root="$1"
+	# In kiss_repo_name="$1" version, if you use "kiss_repo" as local variable name,
+	# it will localize the output name "kiss_repo"
+	local kiss_repo_local="$2"
+	local repo_root="$3"
+	local repo_main_source="$4"
+	local repo_main_auchor="$kiss_root/${kiss_repo_local#*/}"
+	[ -d "$kiss_root/${repo_root#*/}" ] ||  \mkdir -p "$kiss_root/${repo_root#*/}"
+
+	[ ! -e "$repo_main_source" ] &&
+		printf '%s %s\n' '$repo_main_source' "'$repo_main_source' [for $kiss_root/${kiss_repo_local#*/}] does not exist" ||
+	[ -d "$repo_main_auchor" ] || {
+		[ -L "$repo_main_auchor" ] ||
+		[ -h "$repo_main_auchor" ]
+	} || {
+		[ "$(readlink -fn "$repo_root")" != "$(readlink -fn "$REPO_ROOT_IMPL")" ] || {
+			printf '%s %s\n' '$repo_root' "'$repo_root' has local settings and can not be same as '$REPO_ROOT_IMPL'"
+			printf '%s %s\n' '$LAYOUT_INIT' "'$LAYOUT_INIT' has the details"
+			# exit 1
+			return 0
+		}
+		[ ! -L "$repo_main_auchor" ] &&
+		$cmd_link -- "$repo_main_source" "$repo_main_auchor" ||
+		[ "$(readlink -fn "$repo_main_auchor")" = "$(readlink -fn "$repo_main_source")" ] || {
+			\rm -f "$repo_main_auchor" || {
+				printf '%s %s\n' '$repo_root/main' "'$repo_root/main' modification failed"
+				# exit 1
+				return 0
+			}
+
+			$cmd_link -- "$repo_main_source" "$repo_main_auchor"
+		}
+	}
+	# / $kiss_repo_name="$repo_main_source"
+	printf "$RS%s" "$repo_main_source"
+}
+
 # : "${LOGNAME:="$(id -nu)"}" && export LOGNAME
 // env_reset LOGNAME "$(id -nu)"
+: ${KISS_TMPDIR:="/tmp/$USER/kiss"} && export KISS_TMPDIR
+// env_reset SYS_OUTPUT   "$KISS_TMPDIR/logs/sys.log"
+[ -d "${SYS_OUTPUT%/*}" ] || \mkdir -p "${SYS_OUTPUT%/*}"
 
-KISS_PATH=''
+# If you insist to update local system
+# KISS_ROOT= && export KISS_ROOT
+# Or if unset, kiss package manager will set it to '/'
+# [ -z "${KISS_ROOT+x}" ] || unset KISS_ROOT
+#
+# By default use a target address (/opt/kiss or /mnt/kiss)
+# /mnt/kiss might be a mount point of /dev/nvme0n1p3 ... something
+# /opt/kiss normally has larger size (20 GB is recommended) on plain local filesystem
+# Thiese two values are put to prevent from ruining local systemm by accident
+# export KISS_ROOT="/opt/kiss" BOOTSTRAP=
+: ${KISS_ROOT="/opt/kiss"} && export KISS_ROOT
+[ -d "$KISS_ROOT" ] || \mkdir -p "$KISS_ROOT"
 
 // env_reset SHARE_PREFIX_DEV "/opt"
 
 : "${REPO_ROOT:="/var/db/kiss"}" && export REPO_ROOT
 : "${REPO_ROOT_IMPL:="$SHARE_PREFIX_DEV/${REPO_ROOT#*/}"}" && export REPO_ROOT_IMPL
-
-[ -z "${KISS_DEBUG+x}" ] || {
-	# Later ones have higher priority
-	if [ -z "${KISS_PATH:+x}" ]; then
-		KISS_PATH=$REPO_ROOT/kiss-repo-repos
-	else
-		KISS_PATH=$REPO_ROOT/kiss-repo-repos:$KISS_PATH
-	fi
-
-	KISS_PATH=$REPO_ROOT/repos/flatpak/flatpak:$KISS_PATH
-	KISS_PATH=$REPO_ROOT/repos/cemkeylan/personal:$KISS_PATH
-	KISS_PATH=$REPO_ROOT/repos/cemkeylan/editors:$KISS_PATH
-
-	KISS_PATH=$REPO_ROOT/repos/containers:$KISS_PATH
-
-	KISS_PATH=$REPO_ROOT/repos/eudaldgr/extra:$KISS_PATH
-	KISS_PATH=$REPO_ROOT/repos/eudaldgr/libs:$KISS_PATH
-	KISS_PATH=$REPO_ROOT/repos/eudaldgr/garbage:$KISS_PATH
-	KISS_PATH=$REPO_ROOT/repos/eudaldgr/gfx:$KISS_PATH
-	KISS_PATH=$REPO_ROOT/repos/eudaldgr/java:$KISS_PATH
-	KISS_PATH=$REPO_ROOT/repos/eudaldgr/lxqt:$KISS_PATH
-	KISS_PATH=$REPO_ROOT/repos/eudaldgr/office:$KISS_PATH
-	KISS_PATH=$REPO_ROOT/repos/eudaldgr/python:$KISS_PATH
-	KISS_PATH=$REPO_ROOT/repos/eudaldgr/science:$KISS_PATH
-	KISS_PATH=$REPO_ROOT/repos/eudaldgr/themes:$KISS_PATH
-	KISS_PATH=$REPO_ROOT/repos/eudaldgr/video:$KISS_PATH
-
-	KISS_PATH=$REPO_ROOT/repos/periish/audio:$KISS_PATH
-	KISS_PATH=$REPO_ROOT/repos/periish/cmd-utils:$KISS_PATH
-	KISS_PATH=$REPO_ROOT/repos/periish/containers:$KISS_PATH
-	KISS_PATH=$REPO_ROOT/repos/periish/dbus:$KISS_PATH
-	KISS_PATH=$REPO_ROOT/repos/periish/misc:$KISS_PATH
-	KISS_PATH=$REPO_ROOT/repos/periish/ricing:$KISS_PATH
-	KISS_PATH=$REPO_ROOT/repos/periish/xfce4:$KISS_PATH
-
-	KISS_PATH=$REPO_ROOT/noir/wayland:$KISS_PATH
-	KISS_PATH=$REPO_ROOT/noir/testing:$KISS_PATH
-	KISS_PATH=$REPO_ROOT/noir/extra:$KISS_PATH
-	KISS_PATH=$REPO_ROOT/noir/core:$KISS_PATH
-
-	KISS_PATH=$REPO_ROOT/sauzer/xorg:$KISS_PATH
-	KISS_PATH=$REPO_ROOT/sauzer/extra:$KISS_PATH
-	KISS_PATH=$REPO_ROOT/sauzer/core:$KISS_PATH
-
-	KISS_PATH=$REPO_ROOT/dm/im:$KISS_PATH
-	KISS_PATH=$REPO_ROOT/dm/kernel:$KISS_PATH
-	KISS_PATH=$REPO_ROOT/dm/site:$KISS_PATH
-
-	KISS_PATH=$REPO_ROOT/repos/fonts/kiss-fonts:$KISS_PATH
-	KISS_PATH=$REPO_ROOT/repos/himmalerin/modified:$KISS_PATH
-	KISS_PATH=$REPO_ROOT/repos/himmalerin/extra:$KISS_PATH
-	KISS_PATH=$REPO_ROOT/repos/dumpsterfire/wayland:$KISS_PATH
-	KISS_PATH=$REPO_ROOT/repos/dumpsterfire/desktop:$KISS_PATH
-	KISS_PATH=$REPO_ROOT/repos/dumpsterfire/xorg:$KISS_PATH
-	KISS_PATH=$REPO_ROOT/repos/dumpsterfire/extra:$KISS_PATH
-	KISS_PATH=$REPO_ROOT/repos/dumpsterfire/core:$KISS_PATH
-
-	KISS_PATH=$REPO_ROOT/kiss-somethingsomethingstatic/bin:$KISS_PATH
-	KISS_PATH=$REPO_ROOT/kiss-somethingsomethingstatic/wayland:$KISS_PATH
-	KISS_PATH=$REPO_ROOT/kiss-somethingsomethingstatic/community:$KISS_PATH
-	KISS_PATH=$REPO_ROOT/kiss-somethingsomethingstatic/extra:$KISS_PATH
-	KISS_PATH=$REPO_ROOT/kiss-somethingsomethingstatic/core:$KISS_PATH
-
-	# KISS_PATH=$REPO_ROOT/repo/wayland:$KISS_PATH
-	# KISS_PATH=$REPO_ROOT/repo/testing:$KISS_PATH
-	# KISS_PATH=$REPO_ROOT/repo/extra:$KISS_PATH
-	# KISS_PATH=$REPO_ROOT/repo/core:$KISS_PATH
-
-	# KISS_PATH=$REPO_ROOT/repos/mmatongo:$KISS_PATH
-	KISS_PATH=$REPO_ROOT/repos/jedahan:$KISS_PATH
-	KISS_PATH=$REPO_ROOT/repos/ioraff/modified:$KISS_PATH
-	KISS_PATH=$REPO_ROOT/repos/ioraff/dbus:$KISS_PATH
-	KISS_PATH=$REPO_ROOT/repos/ioraff/extra:$KISS_PATH
-	KISS_PATH=$REPO_ROOT/repos/games/equipment:$KISS_PATH
-	KISS_PATH=$REPO_ROOT/repos/games/games:$KISS_PATH
-
-	# KISS_PATH=$REPO_ROOT/repos/lang:$KISS_PATH
-	KISS_PATH=$REPO_ROOT/repos/lang/testing:$KISS_PATH
-	KISS_PATH=$REPO_ROOT/repos/lang/languages:$KISS_PATH
-	KISS_PATH=$REPO_ROOT/repos/lang/extra:$KISS_PATH
-	KISS_PATH=$REPO_ROOT/repos/talyn:$KISS_PATH
-
-	KISS_PATH=$REPO_ROOT/kiss-repo/dbus:$KISS_PATH
-	KISS_PATH=$REPO_ROOT/kiss-repo/extra:$KISS_PATH
-	# KISS_PATH=$REPO_ROOT/kiss-repo/modified:$KISS_PATH
-	# KISS_PATH=$REPO_ROOT/kiss-repo/old:$KISS_PATH
-
-	KISS_PATH=$REPO_ROOT/repos/community/wayland:$KISS_PATH
-	KISS_PATH=$REPO_ROOT/repos/community/extra:$KISS_PATH
-	KISS_PATH=$REPO_ROOT/repos/community/core:$KISS_PATH
-
-	# KISS_PATH=$REPO_ROOT/glasnost/modules/community/community:$KISS_PATH
-	# KISS_PATH=$REPO_ROOT/glasnost/modules/repo/wayland:$KISS_PATH
-	# KISS_PATH=$REPO_ROOT/glasnost/modules/repo/extra:$KISS_PATH
-	# KISS_PATH=$REPO_ROOT/glasnost/modules/repo/core:$KISS_PATH
-
-	KISS_PATH=$REPO_ROOT/community/community:$KISS_PATH
-	KISS_PATH=$REPO_ROOT/boost/community:$KISS_PATH
-	KISS_PATH=$REPO_ROOT/wyverkkiss/wayland:$KISS_PATH
-	KISS_PATH=$REPO_ROOT/wyverkkiss/gnu:$KISS_PATH
-	KISS_PATH=$REPO_ROOT/wyverkkiss/extra:$KISS_PATH
-	KISS_PATH=$REPO_ROOT/wyverkkiss/core:$KISS_PATH
-
-	KISS_PATH=$REPO_ROOT/dilyn/wayland:$KISS_PATH
-	KISS_PATH=$REPO_ROOT/dilyn/gpl:$KISS_PATH
-	KISS_PATH=$REPO_ROOT/dilyn/extra:$KISS_PATH
-	KISS_PATH=$REPO_ROOT/dilyn/core:$KISS_PATH
-
-	if [ -z "${KISS_PATH:+x}" ]; then
-		KISS_PATH=$REPO_ROOT/kiss-llvm
-	else
-		KISS_PATH=$REPO_ROOT/kiss-llvm:$KISS_PATH
-	fi
-
-}
 
 
 # : "${KISS_REPO="$REPO_ROOT/lm"}" && export KISS_REPO
@@ -174,61 +122,144 @@ KISS_PATH=''
 # Actually it is a recommended way to avoid maintaining a seperate repo
 repo_main_source="$REPO_ROOT_IMPL/lm"
 
-newline="
-"
-repo_main() {
+# repo_main "kiss_repo" "$KISS_ROOT" "$KISS_REPO" "$REPO_ROOT" "$repo_main_source"
+kiss_repo="$(// delegate -- repo_main "$KISS_ROOT" "$KISS_REPO" "$REPO_ROOT" "$repo_main_source")"
+printf '%s %s\n' '$kiss_repo' "$kiss_repo" >> "$SYS_OUTPUT"
+KISS_PATH=''
 
-	# local kiss_root="${1:?"Fake root can not be empty"}"
-	# Empty means the local host
-	local kiss_root="${1-}"
-	local repo_main_target="$kiss_root/${KISS_REPO#*/}"
-	[ -d "$kiss_root/${REPO_ROOT#*/}" ] ||  \mkdir -p "$kiss_root/${REPO_ROOT#*/}"
+[ -z "${KISS_DEBUG+x}" ] || {
+	# Later ones have higher priority
+	[ -z "${KISS_PATH:+x}" ] &&
+		KISS_PATH=$REPO_ROOT_IMPL/kiss-repo-repos ||
+		KISS_PATH=$REPO_ROOT_IMPL/kiss-repo-repos:$KISS_PATH
 
-	[ ! -e "$repo_main_source" ] &&
-		printf '%s %s\n' '$repo_main_source' "'$repo_main_source' [for $kiss_root/${KISS_REPO#*/}] does not exist" ||
-	[ -d "$repo_main_target" ] || {
-		[ -L "$repo_main_target" ] ||
-		[ -h "$repo_main_target" ]
-	} || {
-		[ "$(readlink -fn "$REPO_ROOT")" != "$(readlink -fn "$REPO_ROOT_IMPL")" ] || {
-			printf '%s %s\n' '$REPO_ROOT' "'$REPO_ROOT' has local settings and can not be same as '$REPO_ROOT_IMPL'"
-			printf '%s %s\n' '$LAYOUT_INIT' "'$LAYOUT_INIT' has the details"
-			# exit 1
-			return 0
-		}
-		[ ! -L "$repo_main_target" ] &&
-		\ln -sf "$repo_main_source" "$repo_main_target" ||
-		[ "$(readlink -fn "$repo_main_target")" = "$(readlink -fn "$repo_main_source")" ] || {
-			\rm -f "$repo_main_target" || {
-				printf '%s %s\n' '$REPO_ROOT/main' "'$REPO_ROOT/main' modification failed"
-				# exit 1
-				return 0
-			}
+	KISS_PATH=$REPO_ROOT_IMPL/repos/flatpak/flatpak:$KISS_PATH
+	KISS_PATH=$REPO_ROOT_IMPL/repos/cemkeylan/personal:$KISS_PATH
+	KISS_PATH=$REPO_ROOT_IMPL/repos/cemkeylan/editors:$KISS_PATH
 
-			\ln -sf "$repo_main_source" "$repo_main_target"
-		}
-	}
+	KISS_PATH=$REPO_ROOT_IMPL/repos/containers:$KISS_PATH
+
+	KISS_PATH=$REPO_ROOT_IMPL/repos/eudaldgr/extra:$KISS_PATH
+	KISS_PATH=$REPO_ROOT_IMPL/repos/eudaldgr/libs:$KISS_PATH
+	KISS_PATH=$REPO_ROOT_IMPL/repos/eudaldgr/garbage:$KISS_PATH
+	KISS_PATH=$REPO_ROOT_IMPL/repos/eudaldgr/gfx:$KISS_PATH
+	KISS_PATH=$REPO_ROOT_IMPL/repos/eudaldgr/java:$KISS_PATH
+	KISS_PATH=$REPO_ROOT_IMPL/repos/eudaldgr/lxqt:$KISS_PATH
+	KISS_PATH=$REPO_ROOT_IMPL/repos/eudaldgr/office:$KISS_PATH
+	KISS_PATH=$REPO_ROOT_IMPL/repos/eudaldgr/python:$KISS_PATH
+	KISS_PATH=$REPO_ROOT_IMPL/repos/eudaldgr/science:$KISS_PATH
+	KISS_PATH=$REPO_ROOT_IMPL/repos/eudaldgr/themes:$KISS_PATH
+	KISS_PATH=$REPO_ROOT_IMPL/repos/eudaldgr/video:$KISS_PATH
+
+	KISS_PATH=$REPO_ROOT_IMPL/repos/periish/audio:$KISS_PATH
+	KISS_PATH=$REPO_ROOT_IMPL/repos/periish/cmd-utils:$KISS_PATH
+	KISS_PATH=$REPO_ROOT_IMPL/repos/periish/containers:$KISS_PATH
+	KISS_PATH=$REPO_ROOT_IMPL/repos/periish/dbus:$KISS_PATH
+	KISS_PATH=$REPO_ROOT_IMPL/repos/periish/misc:$KISS_PATH
+	KISS_PATH=$REPO_ROOT_IMPL/repos/periish/ricing:$KISS_PATH
+	KISS_PATH=$REPO_ROOT_IMPL/repos/periish/xfce4:$KISS_PATH
+
+	KISS_PATH=$REPO_ROOT_IMPL/noir/wayland:$KISS_PATH
+	KISS_PATH=$REPO_ROOT_IMPL/noir/testing:$KISS_PATH
+	KISS_PATH=$REPO_ROOT_IMPL/noir/extra:$KISS_PATH
+	KISS_PATH=$REPO_ROOT_IMPL/noir/core:$KISS_PATH
+
+	KISS_PATH=$REPO_ROOT_IMPL/sauzer/xorg:$KISS_PATH
+	KISS_PATH=$REPO_ROOT_IMPL/sauzer/extra:$KISS_PATH
+	KISS_PATH=$REPO_ROOT_IMPL/sauzer/core:$KISS_PATH
+
+	KISS_PATH=$REPO_ROOT_IMPL/dm/im:$KISS_PATH
+	KISS_PATH=$REPO_ROOT_IMPL/dm/kernel:$KISS_PATH
+	KISS_PATH=$REPO_ROOT_IMPL/dm/site:$KISS_PATH
+
+	KISS_PATH=$REPO_ROOT_IMPL/repos/fonts/kiss-fonts:$KISS_PATH
+	KISS_PATH=$REPO_ROOT_IMPL/repos/himmalerin/modified:$KISS_PATH
+	KISS_PATH=$REPO_ROOT_IMPL/repos/himmalerin/extra:$KISS_PATH
+	KISS_PATH=$REPO_ROOT_IMPL/repos/dumpsterfire/wayland:$KISS_PATH
+	KISS_PATH=$REPO_ROOT_IMPL/repos/dumpsterfire/desktop:$KISS_PATH
+	KISS_PATH=$REPO_ROOT_IMPL/repos/dumpsterfire/xorg:$KISS_PATH
+	KISS_PATH=$REPO_ROOT_IMPL/repos/dumpsterfire/extra:$KISS_PATH
+	KISS_PATH=$REPO_ROOT_IMPL/repos/dumpsterfire/core:$KISS_PATH
+
+	KISS_PATH=$REPO_ROOT_IMPL/kiss-somethingsomethingstatic/bin:$KISS_PATH
+	KISS_PATH=$REPO_ROOT_IMPL/kiss-somethingsomethingstatic/wayland:$KISS_PATH
+	KISS_PATH=$REPO_ROOT_IMPL/kiss-somethingsomethingstatic/community:$KISS_PATH
+	KISS_PATH=$REPO_ROOT_IMPL/kiss-somethingsomethingstatic/extra:$KISS_PATH
+	KISS_PATH=$REPO_ROOT_IMPL/kiss-somethingsomethingstatic/core:$KISS_PATH
+
+	# KISS_PATH=$REPO_ROOT_IMPL/repo/wayland:$KISS_PATH
+	# KISS_PATH=$REPO_ROOT_IMPL/repo/testing:$KISS_PATH
+	# KISS_PATH=$REPO_ROOT_IMPL/repo/extra:$KISS_PATH
+	# KISS_PATH=$REPO_ROOT_IMPL/repo/core:$KISS_PATH
+
+	# KISS_PATH=$REPO_ROOT_IMPL/repos/mmatongo:$KISS_PATH
+	KISS_PATH=$REPO_ROOT_IMPL/repos/jedahan:$KISS_PATH
+	KISS_PATH=$REPO_ROOT_IMPL/repos/ioraff/modified:$KISS_PATH
+	KISS_PATH=$REPO_ROOT_IMPL/repos/ioraff/dbus:$KISS_PATH
+	KISS_PATH=$REPO_ROOT_IMPL/repos/ioraff/extra:$KISS_PATH
+	KISS_PATH=$REPO_ROOT_IMPL/repos/games/equipment:$KISS_PATH
+	KISS_PATH=$REPO_ROOT_IMPL/repos/games/games:$KISS_PATH
+
+	# KISS_PATH=$REPO_ROOT_IMPL/repos/lang:$KISS_PATH
+	KISS_PATH=$REPO_ROOT_IMPL/repos/lang/testing:$KISS_PATH
+	KISS_PATH=$REPO_ROOT_IMPL/repos/lang/languages:$KISS_PATH
+	KISS_PATH=$REPO_ROOT_IMPL/repos/lang/extra:$KISS_PATH
+	KISS_PATH=$REPO_ROOT_IMPL/repos/talyn:$KISS_PATH
+
+	KISS_PATH=$REPO_ROOT_IMPL/kiss-repo/dbus:$KISS_PATH
+	KISS_PATH=$REPO_ROOT_IMPL/kiss-repo/extra:$KISS_PATH
+	# KISS_PATH=$REPO_ROOT_IMPL/kiss-repo/modified:$KISS_PATH
+	# KISS_PATH=$REPO_ROOT_IMPL/kiss-repo/old:$KISS_PATH
+
+	KISS_PATH=$REPO_ROOT_IMPL/repos/community/wayland:$KISS_PATH
+	KISS_PATH=$REPO_ROOT_IMPL/repos/community/extra:$KISS_PATH
+	KISS_PATH=$REPO_ROOT_IMPL/repos/community/core:$KISS_PATH
+
+	# KISS_PATH=$REPO_ROOT_IMPL/glasnost/modules/community/community:$KISS_PATH
+	# KISS_PATH=$REPO_ROOT_IMPL/glasnost/modules/repo/wayland:$KISS_PATH
+	# KISS_PATH=$REPO_ROOT_IMPL/glasnost/modules/repo/extra:$KISS_PATH
+	# KISS_PATH=$REPO_ROOT_IMPL/glasnost/modules/repo/core:$KISS_PATH
+
+	KISS_PATH=$REPO_ROOT_IMPL/community/community:$KISS_PATH
+	KISS_PATH=$REPO_ROOT_IMPL/boost/community:$KISS_PATH
+	KISS_PATH=$REPO_ROOT_IMPL/wyverkkiss/wayland:$KISS_PATH
+	KISS_PATH=$REPO_ROOT_IMPL/wyverkkiss/gnu:$KISS_PATH
+	KISS_PATH=$REPO_ROOT_IMPL/wyverkkiss/extra:$KISS_PATH
+	KISS_PATH=$REPO_ROOT_IMPL/wyverkkiss/core:$KISS_PATH
+
+	KISS_PATH=$REPO_ROOT_IMPL/dilyn/wayland:$KISS_PATH
+	KISS_PATH=$REPO_ROOT_IMPL/dilyn/gpl:$KISS_PATH
+	KISS_PATH=$REPO_ROOT_IMPL/dilyn/extra:$KISS_PATH
+	KISS_PATH=$REPO_ROOT_IMPL/dilyn/core:$KISS_PATH
+
+	if [ -z "${KISS_PATH:+x}" ]; then
+		KISS_PATH=$REPO_ROOT_IMPL/kiss-llvm
+	else
+		KISS_PATH=$REPO_ROOT_IMPL/kiss-llvm:$KISS_PATH
+	fi
+
 }
 
-repo_main
+path_prepend KISS_PATH "$kiss_repo/extra"
+# [ -z "${KISS_PATH:+x}" ] &&
+# 	KISS_PATH=$kiss_repo/extra ||
+# 	KISS_PATH=$kiss_repo/extra:$KISS_PATH
 
-if [ -z "${KISS_PATH:+x}" ]; then
-	KISS_PATH=$KISS_REPO/extra
-else
-	KISS_PATH=$KISS_REPO/extra:$KISS_PATH
-fi
-
-KISS_PATH=$KISS_REPO/fonts:$KISS_PATH
-KISS_PATH=$KISS_REPO/wayland:$KISS_PATH
-KISS_PATH=$KISS_REPO/system:$KISS_PATH
-KISS_PATH=$KISS_REPO/core:$KISS_PATH
+path_prepend KISS_PATH "$kiss_repo/fonts"
+# KISS_PATH=$kiss_repo/fonts:$KISS_PATH
+path_prepend KISS_PATH "$kiss_repo/wayland"
+# KISS_PATH=$kiss_repo/wayland:$KISS_PATH
+path_prepend KISS_PATH "$kiss_repo/system"
+# KISS_PATH=$kiss_repo/system:$KISS_PATH
+path_prepend KISS_PATH "$kiss_repo/core"
+# KISS_PATH=$kiss_repo/core:$KISS_PATH
 
 # Static version will remove dynamic libraries
-# KISS_PATH=$KISS_REPO/static/bin:$KISS_PATH
-# KISS_PATH=$KISS_REPO/static/community:$KISS_PATH
-# KISS_PATH=$KISS_REPO/static/wayland:$KISS_PATH
-# KISS_PATH=$KISS_REPO/static/extra:$KISS_PATH
-# KISS_PATH=$KISS_REPO/static/core:$KISS_PATH
+# KISS_PATH=$kiss_repo/static/bin:$KISS_PATH
+# KISS_PATH=$kiss_repo/static/community:$KISS_PATH
+# KISS_PATH=$kiss_repo/static/wayland:$KISS_PATH
+# KISS_PATH=$kiss_repo/static/extra:$KISS_PATH
+# KISS_PATH=$kiss_repo/static/core:$KISS_PATH
 
 export KISS_PATH
 
@@ -261,20 +292,6 @@ export KISS_PATH
 # : "${CBUILD:="${KISS_XBUILD_TRIPLE}"}" && export CBUILD
 // env_reset CBUILD "${KISS_XBUILD_TRIPLE}"
 
-# If you insist to update local system
-# KISS_ROOT= && export KISS_ROOT
-# Or if unset, kiss package manager will set it to '/'
-# [ -z "${KISS_ROOT+x}" ] || unset KISS_ROOT
-#
-# By default use a target address (/opt/kiss or /mnt/kiss)
-# /mnt/kiss might be a mount point of /dev/nvme0n1p3 ... something
-# /opt/kiss normally has larger size (20 GB is recommended) on plain local filesystem
-# Thiese two values are put to prevent from ruining local systemm by accident
-export KISS_ROOT="/opt/kiss" BOOTSTRAP=
-[ -d "$KISS_ROOT" ] || \mkdir -p "$KISS_ROOT"
-
-repo_main "$KISS_ROOT"
-
 # : "${KISS_REMOTE_REPO="$KISS_PATH"}" && export KISS_REMOTE_REPO
 // env_reset KISS_REMOTE_REPO "$KISS_PATH"
 # https://github.com/glasnostlinux/glasnost/releases
@@ -301,8 +318,8 @@ repo_main "$KISS_ROOT"
 
 [ -d "$DEST_ROOT" ] || \mkdir -p "$DEST_ROOT"
 # git config --global --add safe.directory "$DEST_ROOT"
-# : "${REPO_BASE:="$KISS_REPO/base"}" && export REPO_BASE
-// env_reset REPO_BASE "$KISS_REPO/base"
+# : "${REPO_BASE:="$kiss_repo/base"}" && export REPO_BASE
+// env_reset REPO_BASE "$kiss_repo/base"
 
 
 
diff --git a/toolchain/env b/toolchain/env
--- a/toolchain/env
+++ b/toolchain/env
@@ -1,11 +1,49 @@
-#!/bin/sh
+#! /bin/sh
+# This file is just a thought, the real applied version depends on
+# /mnt/init/etc/profile.d/kiss-env
+# /usr/bin/kiss-cmake-config
+# /working/os/kiss/usr/bin/kiss
+# /opt/var/db/kiss/lm/underconstruction/llvm/build
+
+alias /='eval'
+alias //='lineno="$LINENO"'
+newline="
+"
+
+SCRIPT_NAME="kiss-env" && export SCRIPT_NAME
+
+[ ! -z "$(type "env_reset" > /dev/null && type "env_reset")" ] &&
+[ ! -z "${SHARE_PREFIX:+x}" ] ||
+{
+	[ -f "/mnt/init/include/route" ] &&
+	. /mnt/init/include/route
+} || {
+	printf '%s %s\n' '$env_reset' "'$env_reset' could not get defined"
+	exit 0
+}
 
 set -efE
 # trap 'Wont handle the "$FUNCNAME" at line "$LINENO"' ERR
 trap 'Wont handle the ERROR at line "$LINENO"' ERR
 
-# Host toolchain root
-HOST_ROOT=/usr
+: ${KISS_ROOT="/opt/kiss"} && export KISS_ROOT
+[ -d "$KISS_ROOT" ] || \mkdir -p "$KISS_ROOT"
+
+# share folder initialization
+// env_reset SHARE_PREFIX_DEV "/opt"
+# [ ! -z "${SHARE_PREFIX+x}" ] || {
+#     if [ -d "/mnt/init" ]; then
+#         export SHARE_PREFIX="/mnt"
+#     elif [ -d "/opt/init" ]; then
+#         export SHARE_PREFIX="/opt"
+#     fi
+# }
+
+export XBUILD_PREFIX=/usr
+# Host toolchain root prefix
+export HOST_ROOT="$KISS_ROOT/$XBUILD_PREFIX"
+export XHOST_PREFIX="$HOST_ROOT"
+
 extend=":$PATH:"
 [ -z "${extend##*:${HOST_ROOT}:*}" ] || eval "export PATH=${HOST_ROOT}\${PATH:+\":\$$PATH\"}"
 
@@ -14,14 +52,6 @@ CXXFLAGS=""
 CPPFLAGS=""
 LDFLAGS=""
 
-# share folder initialization
-[ ! -z "${SHARE_PREFIX+x}" ] || {
-    if [ -d "/mnt/init" ]; then
-        export SHARE_PREFIX="/mnt"
-    elif [ -d "/opt/init" ]; then
-        export SHARE_PREFIX="/opt"
-    fi
-}
 
 export ARCH=x86_64
 export HOST=x86_64
@@ -29,16 +59,17 @@ export TARGET="x86_64-linux-musl"
 export CROSS_COMPILE=${TARGET}
 
 # Target toolchain root
-export SYSROOT=${SHARE_PREFIX}/${TARGET}/sysroot
+export SYSROOT=${SHARE_PREFIX_DEV}/${TARGET}/sysroot
 [ -d ${SYSROOT} ] || doas mkdir -p ${SYSROOT}
 
-export INITRAMFS=${SHARE_PREFIX}/${TARGET}/initramfs
+export INITRAMFS=${SHARE_PREFIX_DEV}/${TARGET}/initramfs
 [ -d ${INITRAMFS} ] || doas mkdir -p ${INITRAMFS}
 
-export DISTDIR=${SHARE_PREFIX}/${TARGET}/make
+export DISTDIR=${SHARE_PREFIX_DEV}/${TARGET}/make
 [ -d ${DISTDIR} ] || doas mkdir -p ${DISTDIR}
+export MAKE_DIR="$DISTDIR"
 
-export XDG_BIN=${SHARE_PREFIX}/local/bin
+export XDG_BIN=${SHARE_PREFIX_DEV}/local/bin
 extend=":$PATH:"
 [ -z "${extend##*:${XDG_BIN}:*}" ] || eval "export PATH=${XDG_BIN}\${PATH:+\":\$$PATH\"}"
 
@@ -51,55 +82,78 @@ doas ln -sf `which clang++` $XDG_BIN/${CROSS_COMPILE}-c++
 doas ln -sf `which clang++` $XDG_BIN/${CROSS_COMPILE}-g++
 doas ln -sf `which clang++` $XDG_BIN/${CROSS_COMPILE}-clang++
 
-for i in ar nm objcopy objdump ranlib strip;do
-    doas ln -sf `which llvm-$i` $XDG_BIN/${CROSS_COMPILE}-$i
+for i in ar nm objcopy objdump ranlib strip; do
+	doas ln -sf `which llvm-$i` $XDG_BIN/${CROSS_COMPILE}-$i
 done
 
+: ${cc:="${CC:-"$( \
+	command -v $(which cc)   ||
+	command -v /usr/lib/ccache/bin/cc ||
+	command -v /usr/bin/cc
+)"}"} || // die 'cc' "compiler not found"
+export cc
+
+: ${cxx:="${CXX:-"$( \
+	command -v $(which c++)   ||
+	command -v /usr/lib/ccache/bin/c++ ||
+	command -v /usr/bin/c++
+)"}"} || // die 'c++' "compiler not found"
+export cxx
+
+export         CC="$cc"
+export        CXX="$cxx"
+
 LDFLAGS="-fuse-ld=lld $LDFLAGS"
-export LD=${HOST_ROOT}/bin/ld.lld
-export HOSTLD=${HOST_ROOT}/bin/ld.lld
+export         LD=${HOST_ROOT}/bin/ld.lld
+export     HOSTLD=${HOST_ROOT}/bin/ld.lld
 
-export CC=${HOST_ROOT}/bin/clang
-export CXX=${HOST_ROOT}/bin/clang++
+export         CC=${HOST_ROOT}/bin/clang
+export        CXX=${HOST_ROOT}/bin/clang++
 
 
-export HOSTCC=${HOST_ROOT}/bin/clang
-export HOSTCXX=${HOST_ROOT}/bin/clang++
+export     HOSTCC=${HOST_ROOT}/bin/clang
+export    HOSTCXX=${HOST_ROOT}/bin/clang++
 
-export AS=${HOST_ROOT}/bin/llvm-as
-export HOSTAS=${HOST_ROOT}/bin/llvm-as
+export         AS=${HOST_ROOT}/bin/llvm-as
+export     HOSTAS=${HOST_ROOT}/bin/llvm-as
 
-export AR=${AR:=${HOST_ROOT}/bin/llvm-ar}
-export HOSTAR=${HOST_ROOT}/bin/llvm-ar
+export         AR=${AR:=${HOST_ROOT}/bin/llvm-ar}
+export     HOSTAR=${HOST_ROOT}/bin/llvm-ar
 
-export NM=${NM:=${HOST_ROOT}/bin/llvm-nm}
-export HOSTNM=${HOST_ROOT}/bin/llvm-nm
+export         NM=${NM:=${HOST_ROOT}/bin/llvm-nm}
+export     HOSTNM=${HOST_ROOT}/bin/llvm-nm
 
-export RANLIB=${HOST_ROOT}/bin/llvm-ranlib
+export     RANLIB=${HOST_ROOT}/bin/llvm-ranlib
 export HOSTRANLIB=${HOST_ROOT}/bin/llvm-ranlib
 
-export STRIP=${HOST_ROOT}/bin/llvm-strip
+export      STRIP=${HOST_ROOT}/bin/llvm-strip
 
-export OBJCOPY=${HOST_ROOT}/bin/llvm-objcopy
+export    OBJCOPY=${HOST_ROOT}/bin/llvm-objcopy
 
-export OBJDUMP=${HOST_ROOT}/bin/llvm-objdump
+export    OBJDUMP=${HOST_ROOT}/bin/llvm-objdump
 
-export READELF=${HOST_ROOT}/bin/llvm-readelf
+export    READELF=${HOST_ROOT}/bin/llvm-readelf
 
-# llvm-ranlib -> llvm-ar*
-# llvm-lib -> llvm-ar*
-# llvm-dlltool -> llvm-ar*
-# llvm-strip -> llvm-objcopy*
-# llvm-otool -> llvm-objdump*
-# llvm-install-name-tool -> llvm-objcopy*
-# llvm-bitcode-strip -> llvm-objcopy*
-# llvm-windres -> llvm-rc*
-# llvm-readelf -> llvm-readobj*
-# llvm-addr2line -> llvm-symbolizer*
+# llvm-ranlib             -> llvm-ar*
+# llvm-lib                -> llvm-ar*
+# llvm-dlltool            -> llvm-ar*
+# llvm-strip              -> llvm-objcopy*
+# llvm-otool              -> llvm-objdump*
+# llvm-install-name-tool  -> llvm-objcopy*
+# llvm-bitcode-strip      -> llvm-objcopy*
+# llvm-windres            -> llvm-rc*
+# llvm-readelf            -> llvm-readobj*
+# llvm-addr2line          -> llvm-symbolizer*
 
 # https://docs.kernel.org/kbuild/llvm.html
 export LLVM_IAS=1
 export LLVM=1
+export LLVM_DEFAULT_TARGET_TRIPLE="$KISS_XBUILD_TRIPLE"
+# compiler_version="$($cc --version | grep version | awk -F " " '{print $NF}')"
+toolchain_version="$($XBUILD_PREFIX/bin/llvm-config --version | tr -d '[:alpha:]')"
+
+export C_INCLUDE_PATH="$XBUILD_PREFIX/lib/clang/$toolchain_version/include:$XBUILD_PREFIX/include"
+export CPLUS_INCLUDE_PATH="$XBUILD_PREFIX/include/$LLVM_DEFAULT_TARGET_TRIPLE/c++/v1/:$XBUILD_PREFIX/include/c++/v1/:$XBUILD_PREFIX/lib/clang/$toolchain_version/include:$XBUILD_PREFIX/include"
 
 export LLVM_BIN=${LLVM_BIN:=$(${HOST_ROOT}/bin/llvm-config --bindir)}
 COMPILER_RESOURCE_DIR=$("$CC" --print-resource-dir)
@@ -131,10 +185,10 @@ CXXFLAGS="$CFLAGS"
 
 HOST_LLVM_VERSION=$(llvm-config --version)
 # Don't worry, it is hard coded in LLVM
-CXX_STANDARD_VER=c++20
+CXX_STANDARD_VER=c++23
 
-[ ! -z "${CC+x}" ]  || CC=/usr/bin/clang
-[ ! -z "${CXX+x}" ] || CXX=/usr/bin/clang++
+# [ ! -z "${CC+x}" ]  || CC=/usr/bin/clang
+# [ ! -z "${CXX+x}" ] || CXX=/usr/bin/clang++
 
 search_config="/usr/include/c++/v1/__config"
 [ ! -f "$search_config" ] ||
@@ -145,24 +199,24 @@ search_config="$(find /usr/include -type f -name "__config" | grep -v "experimen
 # /usr/include/c++/v1/experimental/__config
 # /usr/include/c++/v1/__config
 for config_file in $search_config; do
-    [ ! -f "$config_file" ] || {
-        _LIBCPP_VERSION=$(printf "#include <$config_file>\nint main () { return 0;}" |
-        $CC -E -stdlib=libc++ -x c++ -dM - | grep " _LIBCPP_VERSION " |
-        awk '{print $3}');
-        [ -z "${_LIBCPP_VERSION+x}" ] || {
-            export _LIBCPP_VERSION="$_LIBCPP_VERSION"
-            break
-        }
-    }
+	[ ! -f "$config_file" ] || {
+		_LIBCPP_VERSION=$(printf "#include <$config_file>\nint main () { return 0;}" |
+		$CC -E -stdlib=libc++ -x c++ -dM - | grep " _LIBCPP_VERSION " |
+		awk '{print $3}');
+		[ -z "${_LIBCPP_VERSION+x}" ] || {
+			export _LIBCPP_VERSION="$_LIBCPP_VERSION"
+			break
+		}
+	}
 done
 # HAS_LIBCXX=$(printf "#include <ciso646>\nint main () {}" | $CC -E -stdlib=libc++ -x c++ -dM - | grep _LIBCPP_VERSION | awk '{print $2}')
 # HAS_LIBCXX=$(printf "#include <__config>\nint main () {}" | $CXX -E -stdlib=libc++ -x c++ -dM - | grep _LIBCPP_VERSION | awk '{print $2}')
 
 if [ ! -z "${_LIBCPP_VERSION+x}" ]; then
-    LLVM_ENABLE_LIBCXX="ON"
-    LLVM_ENABLE_LIBCXXABI="ON"
-    LIBCXX_PREFIX=""
-    CXXFLAGS="-D_LIBCPP_PROVIDES_DEFAULT_RUNE_TABLE=1 $CXXFLAGS"
+	LLVM_ENABLE_LIBCXX="ON"
+	LLVM_ENABLE_LIBCXXABI="ON"
+	LIBCXX_PREFIX=""
+	CXXFLAGS="-D_LIBCPP_PROVIDES_DEFAULT_RUNE_TABLE=1 $CXXFLAGS"
 LDFLAGS="${LDFLAGS} \
 -lc++ \
 -lc++abi \
@@ -170,7 +224,7 @@ LDFLAGS="${LDFLAGS} \
 -unwindlib=libunwind \
 "
 else
-    LIBCXX_PREFIX="std"
+	LIBCXX_PREFIX="std"
 fi
 
 CXXFLAGS="$CXXFLAGS -stdlib=lib${LIBCXX_PREFIX}c++"
@@ -223,7 +277,7 @@ LDFLAGS="${LDFLAGS} \
 -nodefaultlibs \
 -lpthread \
 -no-pie \
--Wl,-rpath-link ${HOST_LLVM_LIBDIR} \
+-Wl,-rpath ${HOST_LLVM_LIBDIR} \
 -Wl,-rpath=${HOST_ROOT}/lib \
 -Wl,-L ${HOST_LLVM_LIBDIR} \
 -L${HOST_ROOT}/lib \
@@ -264,10 +318,10 @@ export LDFLAGS="${LDFLAGS}"
 # # export CPPFLAGS+=-resource-dir=$("$CC" --print-resource-dir)
 # # export CFLAGS+=-resource-dir=$("$CC" --print-resource-dir)
 # # declare -A CML
-#     CMLFS=${SHARE_PREFIX}/cmlfs
-#     CML_BIN_DIR=${SHARE_PREFIX}/cmlfs
+#     CMLFS=${SHARE_PREFIX_DEV}/cmlfs
+#     CML_BIN_DIR=${SHARE_PREFIX_DEV}/cmlfs
 #     export CMLFS=${CMLFS}
-#     export CML_BIN_DIR=${SHARE_PREFIX}/cmlfs
+#     export CML_BIN_DIR=${SHARE_PREFIX_DEV}/cmlfs
 #     [ -d ${CML_BIN_DIR} ] || doas mkdir -p ${CML_BIN_DIR}
 # 
 #     CML_BUILD_DIR=${BUILD_PREFIX}/toolchain/cmlfs
