"init/functions" including unified

diff --git a/init/etc/profile.d/xdg-runtime-dir b/init/etc/profile.d/xdg-runtime-dir
--- a/init/etc/profile.d/xdg-runtime-dir
+++ b/init/etc/profile.d/xdg-runtime-dir
@@ -1,17 +1,34 @@
 #! /bin/sh
 
-case "$(type env_reset)" in *"function"*|*"alias"*) ;;
-	*)
-	_env_reset() {
-		local env_key_name="${1:?"env_reset needs a key"}"
-		local env_value="${2:?"env_reset '$1' needs a value"}"
-		/ "[ \"\${$env_key_name-}\" = \"$env_value\" ]" || {
-			# / "echo \"Original \\$\$env_key_name = \${$env_key_name-}\""
-			/ "$env_key_name=\"$env_value\"" && / "export \"$env_key_name\""
-		}
+# share folder initialization
+[ ! -z "${SHARE_PREFIX:+x}" ] || {
+	[ -d "/mnt/init" ] &&
+	{ SHARE_PREFIX="/mnt" && export SHARE_PREFIX; } || {
+		[ -d "/opt/init" ] &&
+		{ SHARE_PREFIX="/opt" && export SHARE_PREFIX; } ||
+		printf '%s %s\n' '$SHARE_PREFIX' "not found"
 	}
-	alias env_reset='_env_reset'
-esac
+}
+
+_functions="$SHARE_PREFIX/init/functions"
+[ ! -f "$_functions" ] && {
+	printf '%s %s\n' '$_functions' "'$_functions' does not exist"
+	exit 0
+} ||
+	. "$_functions"
+
+# case "$(type env_reset)" in *"function"*|*"alias"*) ;;
+# 	*)
+# 	_env_reset() {
+# 		local env_key_name="${1:?"env_reset needs a key"}"
+# 		local env_value="${2:?"env_reset '$1' needs a value"}"
+# 		/ "[ \"\${$env_key_name-}\" = \"$env_value\" ]" || {
+# 			# / "echo \"Original \\$\$env_key_name = \${$env_key_name-}\""
+# 			/ "$env_key_name=\"$env_value\"" && / "export \"$env_key_name\""
+# 		}
+# 	}
+# 	alias env_reset='_env_reset'
+# esac
 
 # : ${UID="$(id -u)"} && export UID
 env_reset UID "$(id -u)"
