"wpa" updated

diff --git a/local/bin/backup b/local/bin/backup
--- a/local/bin/backup
+++ b/local/bin/backup
@@ -1,15 +1,16 @@
 #!/bin/sh -efE
 
-BACKUP_ROOT="$HOME/downloads/linux/glasnost/glasnost-chroot-x86_64"
-
-SRC_ROOT="/mnt/kiss"
+BACKUP_ROOT="$HOME/downloads/linux/kissllm/chroot-x86_64"
 
 if [ "${HOSTNAME}" = "kiss" ]; then
-    SRC_ROOT=""
-elif [ "$(/usr/bin/whoami)" = "root" ]; then
-    /mnt/load-kiss
+    KISS_ROOT=""
 else
-    doas /mnt/load-kiss
+    KISS_ROOT="/mnt/kiss"
+    if [ "$(/usr/bin/whoami)" = "root" ]; then
+        /mnt/load-kiss
+    else
+        doas /mnt/load-kiss
+    fi
 fi
 
 if [ "$(/usr/bin/whoami)" = "root" ]; then
@@ -21,46 +22,46 @@ fi
 [ -d "${BACKUP_ROOT}" ] || \mkdir -p "${BACKUP_ROOT}"
 [ -d "${BACKUP_ROOT}/boot" ] || \mkdir -p "${BACKUP_ROOT}/boot"
 
-if ! eval '$copy "${SRC_ROOT}/boot" "${BACKUP_ROOT}/"'; then
-    echo "Failed to copy '${SRC_ROOT}/boot'"
+if ! eval '$copy "${KISS_ROOT}/boot" "${BACKUP_ROOT}/"'; then
+    echo "Failed to copy '${KISS_ROOT}/boot'"
     exit 1
 else
-    echo "Succeeded to copy '${SRC_ROOT}/boot'"
+    echo "Succeeded in copying '${KISS_ROOT}/boot'"
 fi
 
 [ -d "${BACKUP_ROOT}/etc" ] || \mkdir -p "${BACKUP_ROOT}/etc"
 
-if ! eval '$copy "${SRC_ROOT}/etc" "${BACKUP_ROOT}/"'; then
-    echo "Failed to copy '${SRC_ROOT}/etc'"
+if ! eval '$copy "${KISS_ROOT}/etc" "${BACKUP_ROOT}/"'; then
+    echo "Failed to copy '${KISS_ROOT}/etc'"
     exit 1
 else
-    echo "Succeeded to copy '${SRC_ROOT}/etc'"
+    echo "Succeeded in copying '${KISS_ROOT}/etc'"
 fi
 
 [ -d "${BACKUP_ROOT}/usr" ] || \mkdir -p "${BACKUP_ROOT}/usr"
 
-cd  "${SRC_ROOT}/usr"
-for dir in $(doas \ls -1 "${SRC_ROOT}/usr"); do
+cd  "${KISS_ROOT}/usr"
+for dir in $(doas \ls -1 "${KISS_ROOT}/usr"); do
     [ ! -d "$dir" ] || [ "$dir" = "src" ] || {
-        if ! eval '$copy "${SRC_ROOT}/usr/$dir" "${BACKUP_ROOT}/usr/"'; then
-            echo "Failed to copy '${SRC_ROOT}/usr/$dir'"
+        if ! eval '$copy "${KISS_ROOT}/usr/$dir" "${BACKUP_ROOT}/usr/"'; then
+            echo "Failed to copy '${KISS_ROOT}/usr/$dir'"
             exit 1
         else
-            echo "Succeeded to copy '${SRC_ROOT}/usr/$dir'"
+            echo "Succeeded in copying '${KISS_ROOT}/usr/$dir'"
         fi
     }
 done
 
 [ -d "${BACKUP_ROOT}/var/db/kiss/installed" ] || \mkdir -p "${BACKUP_ROOT}/var/db/kiss/installed"
 
-if ! eval '$copy "${SRC_ROOT}/var/db/kiss/installed" "${BACKUP_ROOT}/var/db/kiss/"'; then
-    echo "Failed to copy '${SRC_ROOT}/var/db/kiss/installed'"
+if ! eval '$copy "${KISS_ROOT}/var/db/kiss/installed" "${BACKUP_ROOT}/var/db/kiss/"'; then
+    echo "Failed to copy '${KISS_ROOT}/var/db/kiss/installed'"
     exit 1
 else
-    echo "Succeeded to copy '${SRC_ROOT}/var/db/kiss/installed'"
+    echo "Succeeded in copying '${KISS_ROOT}/var/db/kiss/installed'"
 fi
 
 sync
 
 echo "\$BACKUP_ROOT = '${BACKUP_ROOT}'"
-echo "\$SRC_ROOT    = '${SRC_ROOT}'"
+echo "\$KISS_ROOT   = '${KISS_ROOT}'"
diff --git a/local/bin/wpa b/local/bin/wpa
--- a/local/bin/wpa
+++ b/local/bin/wpa
@@ -1,24 +1,30 @@
 #!/bin/sh
-if [ -z "$1" ]; then
-    echo "Input \$1 for switch, please"
-else
-    wap_list="$(ps -e | grep wpa_supplicant|grep conf | cut -d ' ' -f 1)"
-    for wpa in $wap_list; do doas kill -9 $wpa; done
 
-    # https://www.linuxquestions.org/questions/slackware-14/wpa_supplicant-failed-to-initialize-driver-4175668012/
-    # bring up the ethernet adapter
-    doas /sbin/ip link set dev wlan0 up
+config="$1"
+[ ! -z "$1" ] ||
+config=$HOME/.config/wpa_supplicant/wpa_supplicant.conf
+echo "\$config = $config"
+[ -f "$config" ] ||
+{ echo "Input valid \$1 for switch, please"; exit 1; }
+interface=$(\ls /sys/class/ieee80211/*/device/net)
+[ ! -z "$interface" ] || interface=$(iw dev | awk '$1=="Interface"{print $2}')
+echo "\$interface = $interface"
+wpa_list="$(ps -e | grep wpa_supplicant|grep conf | cut -d ' ' -f 1)"
+for wpa in $wpa_list; do doas kill -9 $wpa; done
 
-    # flush its configuration
-    doas /sbin/ip address flush dev wlan0
+# https://www.linuxquestions.org/questions/slackware-14/wpa_supplicant-failed-to-initialize-driver-4175668012/
+# bring up the ethernet adapter
+doas /sbin/ip link set dev $interface up
 
-    # you might need an IP address before doing the IEEE 802.1X authentication with wpa_supplicant
-    # /sbin/dhclient eth0
-    doas /sbin/dhcpcd wlan0
+# flush its configuration
+doas /sbin/ip address flush dev $interface
 
-    # then run wpa_supplicant
-    # doas wpa_supplicant -D nl80211 -B -i wlan0 -c $HOME/.config/wpa_supplicant/wpa_supplicant.conf
-    doas wpa_supplicant -D nl80211 -i wlan0 -c $HOME/.config/wpa_supplicant/$1.conf > $HOME/.config/wpa_supplicant/.wpa.log &
-    sleep 3s
-    doas /sbin/dhcpcd wlan0
-fi
+# you might need an IP address before doing the IEEE 802.1X authentication with wpa_supplicant
+# /sbin/dhclient eth0
+doas su dhcpcd /sbin/dhcpcd $interface
+
+# then run wpa_supplicant
+# doas wpa_supplicant -D nl80211 -B -i $interface -c $HOME/.config/wpa_supplicant/wpa_supplicant.conf
+doas wpa_supplicant -D nl80211 -i $interface -c $config > $HOME/.config/wpa_supplicant/.wpa.log &
+sleep 3s
+doas su dhcpcd /sbin/dhcpcd $interface
