Clipboard operations optimized

diff --git a/local/bin/backup b/local/bin/backup
--- a/local/bin/backup
+++ b/local/bin/backup
@@ -1,4 +1,4 @@
-#!/usr/bin/env sh
+#!/bin/sh -efE
 
 BACKUP_ROOT="$HOME/downloads/linux/glasnost/glasnost-chroot-x86_64"
 
@@ -7,44 +7,60 @@ SRC_ROOT="/mnt/kiss"
 if [ "${HOSTNAME}" = "kiss" ]; then
     SRC_ROOT=""
 elif [ "$(/usr/bin/whoami)" = "root" ]; then
-    load-kiss
+    /mnt/load-kiss
 else
-    doas load-kiss
+    doas /mnt/load-kiss
 fi
 
 if [ "$(/usr/bin/whoami)" = "root" ]; then
-    copy='rsync -aqz'
+    copy="rsync -aqz"
 else
-    copy='doas rsync -aqz'
+    copy="doas rsync -aqz"
 fi
 
-[ ! -d "${BACKUP_ROOT}" ] && mkdir -p "${BACKUP_ROOT}"
-[ ! -d "${BACKUP_ROOT}/boot" ] && mkdir -p "${BACKUP_ROOT}/boot"
+[ -d "${BACKUP_ROOT}" ] || \mkdir -p "${BACKUP_ROOT}"
+[ -d "${BACKUP_ROOT}/boot" ] || \mkdir -p "${BACKUP_ROOT}/boot"
+
 if ! eval '$copy "${SRC_ROOT}/boot" "${BACKUP_ROOT}/"'; then
-    echo 'Failed to copy "${SRC_ROOT}/boot"'
+    echo "Failed to copy '${SRC_ROOT}/boot'"
     exit 1
+else
+    echo "Succeeded to copy '${SRC_ROOT}/boot'"
 fi
-[ ! -d "${BACKUP_ROOT}/etc" ] && mkdir -p "${BACKUP_ROOT}/etc"
+
+[ -d "${BACKUP_ROOT}/etc" ] || \mkdir -p "${BACKUP_ROOT}/etc"
+
 if ! eval '$copy "${SRC_ROOT}/etc" "${BACKUP_ROOT}/"'; then
-    echo 'Failed to copy "${SRC_ROOT}/etc"'
+    echo "Failed to copy '${SRC_ROOT}/etc'"
     exit 1
+else
+    echo "Succeeded to copy '${SRC_ROOT}/etc'"
 fi
-[ ! -d "${BACKUP_ROOT}/usr" ] && mkdir -p "${BACKUP_ROOT}/usr"
-sub_usr=$(doas ls "${SRC_ROOT}/usr")
-# eval '$copy "${SRC_ROOT}/usr" "${BACKUP_ROOT}/"'
-for dir in $sub_usr; do
-[ -d "$dir" ] && [ "$dir" != "src" ] && {
-    if ! eval '$copy "${SRC_ROOT}/usr/$dir" "${BACKUP_ROOT}/usr/"'; then
-        echo 'Failed to copy "${SRC_ROOT}/usr/$dir"'
-        exit 1
-    fi
-}
+
+[ -d "${BACKUP_ROOT}/usr" ] || \mkdir -p "${BACKUP_ROOT}/usr"
+
+cd  "${SRC_ROOT}/usr"
+for dir in $(doas \ls -1 "${SRC_ROOT}/usr"); do
+    [ ! -d "$dir" ] || [ "$dir" = "src" ] || {
+        if ! eval '$copy "${SRC_ROOT}/usr/$dir" "${BACKUP_ROOT}/usr/"'; then
+            echo "Failed to copy '${SRC_ROOT}/usr/$dir'"
+            exit 1
+        else
+            echo "Succeeded to copy '${SRC_ROOT}/usr/$dir'"
+        fi
+    }
 done
-[ ! -d "${BACKUP_ROOT}/var/db/kiss/installed" ] && mkdir -p "${BACKUP_ROOT}/var/db/kiss/installed"
+
+[ -d "${BACKUP_ROOT}/var/db/kiss/installed" ] || \mkdir -p "${BACKUP_ROOT}/var/db/kiss/installed"
+
 if ! eval '$copy "${SRC_ROOT}/var/db/kiss/installed" "${BACKUP_ROOT}/var/db/kiss/"'; then
-    echo 'Failed to copy "${SRC_ROOT}/var/db/kiss/installed"'
+    echo "Failed to copy '${SRC_ROOT}/var/db/kiss/installed'"
     exit 1
+else
+    echo "Succeeded to copy '${SRC_ROOT}/var/db/kiss/installed'"
 fi
+
 sync
-echo "BACKUP_ROOT = ${BACKUP_ROOT}"
-echo "SRC_ROOT    = ${SRC_ROOT}"
+
+echo "\$BACKUP_ROOT = '${BACKUP_ROOT}'"
+echo "\$SRC_ROOT    = '${SRC_ROOT}'"
diff --git a/local/bin/restore b/local/bin/restore
--- a/local/bin/restore
+++ b/local/bin/restore
@@ -7,7 +7,21 @@ TARET_ROOT="/mnt/kiss"
 if [ "${HOSTNAME}" = "kiss" ]; then
     TARET_ROOT=""
 else
-    doas load-kiss
+    doas /mnt/load-kiss
 fi
 
-doas \cp -rf "${BACKUP_ROOT}/*" "${TARET_ROOT}/"
+if [ "$(/usr/bin/whoami)" = "root" ]; then
+    copy="rsync -aqz"
+else
+    copy="doas rsync -aqz"
+fi
+
+cd "${BACKUP_ROOT}"
+for dir in $(doas \ls -1 "${BACKUP_ROOT}"); do
+    if ! eval '$copy "${BACKUP_ROOT}/$dir" "${TARET_ROOT}/"'; then
+        echo "Failed to copy '${BACKUP_ROOT}/$dir'"
+        exit 1
+    else
+        echo "Succeeded to copy '${BACKUP_ROOT}/$dir'"
+    fi
+done
