Added init/terminal/foot/foot.ini

diff --git a/local/bin/q b/local/bin/q
--- a/local/bin/q
+++ b/local/bin/q
@@ -1,4 +1,4 @@
-#!/usr/bin/env sh
+#!/bin/sh
 
 # How to use:
 # Query
@@ -16,19 +16,27 @@ else
     index=0
     target="${1}"
     selected=
+    ver_selected=
+    sub_ver_selected=
     packages="$(find "/var/db/kiss" \( -type d -o -type l \) -name "${target}")"
     for pack in $packages
     do
         [ -d "$pack" ] && [ -f "$pack/version" ] && {
-            printf "%-4d %-15s %-75s\n" $((index)) "$(cat "$pack/version")" "$pack"
+            read -r ver sub_ver 2>/dev/null < "$pack/version" || {
+                printf "%s\n" "Failed to read version file ($pack/version)"
+                exit 1
+            }
+            printf "%-4d %-9s %-4s %s\n" $((index)) "$ver" "$sub_ver" "$pack"
             if [ -n "$2" ] && [ $index = $2 ]; then
                 selected="$pack"
+                ver_selected="$ver"
+                sub_ver_selected="$sub_ver"
             fi
             index=$(($index + 1))
         }
     done
     if [ -n "$selected" ]; then
-        printf "\n%s\n%-4d %-15s %-75s\n\n" "Selected package:" $2 "$(cat "$selected/version")" "$selected"
+        printf "\n%s\n%-4d %-9s %-4s %s\n\n" "Selected package:" $2  "$ver_selected" "$sub_ver_selected" "$selected"
         dir="$(dirname "$selected")"
         base="$(basename "$selected")"
         if [ -z "${USE_GMAKE}" ]; then
@@ -41,8 +49,8 @@ else
             [ "$(readlink "${build_root}/bin/make")"   != "/usr/bin/gmake" ] && \ln -sf "/usr/bin/gmake" "${build_root}/bin/make"
             export PATH="${build_root}/bin:$PATH"
         fi
-        eval "KISS_PATH=$dir kiss c $base"
-        eval "KISS_PATH=$dir kiss b $base"
-        eval "KISS_PATH=$dir kiss i $base"
+        eval "KISS_PATH=$dir /usr/bin/kiss c $base"
+        eval "KISS_PATH=$dir /usr/bin/kiss b $base"
+        eval "KISS_PATH=$dir /usr/bin/kiss i $base"
     fi
 fi
