tmux copy-mode-vi search with selection

diff --git a/lib/mount_smart b/lib/mount_smart
--- a/lib/mount_smart
+++ b/lib/mount_smart
@@ -3,92 +3,98 @@
 # mount_smart target source
 set -eE
 trace_line() {
-    local func_name="$1"
-    local lineo="$2"
-    echo "Error on function '$func_name' at '$lineo'"
+	local func_name="$1"
+	local lineo="$2"
+	echo "Error on function '$func_name' at '$lineo'"
 }
 
 # trap 'trace_line "$FUNCNAME" "$LINENO"' ERR || :
 
 target_exists () {
-    set -eE
-    # trap 'trace_line "$FUNCNAME" "$LINENO"' ERR
-    local des="$1"
-    # echo "In target_exists, \$des = $des"
-    # alredy_mounts="$(lsblk|grep $des | rev | cut -d" " -f1 | rev | tr '\n' ' ')"
-    # https://stackoverflow.com/questions/9422461/check-if-directory-mounted-with-bash
-    local found=0
-    local result=1
-    for I in $(mount | grep "$des" | awk "{print \$3}"); do
-        [ "$I" != "$des" ] || found=$(( $found + 1 ))
-    done
-    [ "$found" -eq "0" ] || result=0
-    echo "$des found $found time(s)"
-    return "$result"
+	set -eE
+	# trap 'trace_line "$FUNCNAME" "$LINENO"' ERR
+	local des="$1"
+	# echo "In target_exists, \$des = $des"
+	# alredy_mounts="$(lsblk|grep $des | rev | cut -d" " -f1 | rev | tr '\n' ' ')"
+	# https://stackoverflow.com/questions/9422461/check-if-directory-mounted-with-bash
+	local found=0
+	local result=1
+	for I in $(mount | grep "$des" | awk "{print \$3}"); do
+		[ "$I" != "$des" ] || found=$(( $found + 1 ))
+	done
+	[ "$found" -eq "0" ] || result=0
+	echo "$des found $found time(s)"
+
+	return $result
 }
 
 # "src" mounted
 src_mounted () {
-    set -eE
-    # trap 'trace_line "$FUNCNAME" "$LINENO"' ERR
-    local src="${1:?"Must has first parameter"}"
-    local result=1
-    # [ -z "$src" ] && return "$result" ||
-    [ -z "$(df "${src}" 2>/dev/null | grep -v "Filesystem" | \
-        grep "${src}" | awk "{print \$1}")" ] ||
-        # echo $(df ${src} | grep ${src} | awk '{print $1}')
-    result=0
-    return "$result"
+	set -eE
+	# trap 'trace_line "$FUNCNAME" "$LINENO"' ERR
+	local src="${1:?"Must has first parameter"}"
+	local result=1
+	# [ -z "$src" ] && return "$result" ||
+	[ -z "$(df "${src}" 2>/dev/null | grep -v "Filesystem" | \
+		grep "${src}" | awk "{print \$1}")" ] || result=0
+		# echo $(df ${src} | grep ${src} | awk '{print $1}')
+
+	return $result
 }
 
 # "src" mounted and target match "des"
 dev_mounted_target () {
-    set -eE
-    # trap 'trace_line "$FUNCNAME" "$LINENO"' ERR
-    local des="${1:?"Must not empty"}"
-    local src="${2:?"Must not empty"}"
+	set -eE
+	# trap 'trace_line "$FUNCNAME" "$LINENO"' ERR
+	local des="${1:?"Must not empty"}"
+	local src="${2:?"Must not empty"}"
 
-    local des_mounted_target=
-    local result=1
+	local des_mounted_target=
+	local result=1
 
-    # https://stackoverflow.com/questions/762631/find-out-if-a-command-exists-on-posix-system
+	# https://stackoverflow.com/questions/762631/find-out-if-a-command-exists-on-posix-system
 
-    command -v findmnt > /dev/null && {
-        # mapped=("${(@f)$(findmnt --kernel -n --list | \
-        # grep -v '\[' | grep $src | awk '{print $1}')}")
-        # util-linux
-        mapped="$(findmnt --kernel -n --list | \
-                grep -v '\[' | grep "$src" | awk "{print \$1}" | tr '\n' ' ')"
+	command -v findmnt > /dev/null && {
+		# mapped=("${(@f)$(findmnt --kernel -n --list | \
+		# grep -v '\[' | grep $src | awk '{print $1}')}")
+		# util-linux
+		mapped="$(findmnt --kernel -n --list | \
+				grep -v '\[' | grep "$src" | awk "{print \$1}" | tr '\n' ' ')"
 
-        for I in $mapped; do
-            [ "$des" != '$I' ] || des_mounted_target="$des"
-        done
-    }
+		for I in $mapped; do
+			[ "$des" != '$I' ] || des_mounted_target="$des"
+		done
+	}
 
-    [ -n "$des_mounted_target" ] ||
-    des_mounted_target="$(df "${src}" 2>/dev/null | \
-            grep -v "Filesystem" | grep "${src}" | awk "{print \$6}" | tr '\n' ' ')"
+	[ -n "$des_mounted_target" ] ||
+	des_mounted_target="$(df "${src}" 2>/dev/null | \
+			grep -v "Filesystem" | grep "${src}" | awk "{print \$6}" | tr '\n' ' ')"
 
-    [ "$des" != "$des_mounted_target" ] || result=0
+	[ "$des" != "$des_mounted_target" ] || result=0
 
-    return "$result"
+	return $result
 }
 
 mount_smart () {
-    set -eE
-    # trap 'trace_line "$FUNCNAME" "$LINENO"' ERR
-    local target="${1:?"Must not empty"}"
-    local src="${2:?"Must not empty"}"
-    [ -d "$target" ] || {
-        mkdir -p "$target"
-        chmod --quiet 0755 "$target"
-    }
-    src_mounted "$src" || { mount $src $target; return 0; }
-    dev_mounted_target "$target" "$src" || {
-        [ -z "${3}" ] && local option="-o bind" || local option="${3}"
-        local des_mounted_target="$(df "${src}" 2>/dev/null | \
-                grep -v "Filesystem" | grep "${src}" | awk "{print \$6}" | tr '\n' ' ')"
-        mount $option $des_mounted_target $target
-        echo "src=$src, target=$target, binded"
-    }
+	set -eE
+	local result=1
+	# trap 'trace_line "$FUNCNAME" "$LINENO"' ERR
+	local target="${1:?"Must not empty"}"
+	local src="${2:?"Must not empty"}"
+	[ -d "$target" ] || {
+		mkdir -p "$target"
+		chmod --quiet 0755 "$target"
+	}
+	src_mounted "$src" || { mount $src $target; return 0; }
+	dev_mounted_target "$target" "$src" || {
+		[ -z "${3}" ] && local option="-o bind" || local option="${3}"
+		local des_mounted_target="$(df "${src}" 2>/dev/null | \
+				grep -v "Filesystem" | grep "${src}" | awk "{print \$6}" | tr '\n' ' ')"
+		mount $option $des_mounted_target $target && result=$?
+		echo "src=$src, target=$target, binded"
+	}
+
+	return $result
 }
+
+
diff --git a/local/bin/backup b/local/bin/backup
--- a/local/bin/backup
+++ b/local/bin/backup
@@ -3,71 +3,71 @@
 BACKUP_ROOT="$HOME/downloads/linux/kissllm/chroot-x86_64"
 
 if [ "${HOSTNAME}" = "kiss" ]; then
-    KISS_ROOT=""
+	KISS_ROOT=""
 else
-    KISS_ROOT="/mnt/kiss"
-    if [ "$(/usr/bin/whoami)" = "root" ]; then
-        /mnt/load-kiss
-    else
-        doas /mnt/load-kiss
-    fi
+	KISS_ROOT="/mnt/kiss"
+	if [ "$(/usr/bin/whoami)" = "root" ]; then
+		/mnt/load-kiss
+	else
+		doas /mnt/load-kiss
+	fi
 fi
 
 if [ "$(/usr/bin/whoami)" = "root" ]; then
-    copy="rsync -aqz --delete-after"
-    # copy="/usr/bin/cp -rf"
+	copy_way="rsync -aqzpogDX --delete-after"
+	# copy_way="/usr/bin/cp -rf"
 else
-    copy="doas rsync -aqz --delete-after"
-    # copy="doas /usr/bin/cp -rf"
+	copy_way="doas rsync -aqzpogDX --delete-after"
+	# copy_way="doas /usr/bin/cp -rf"
 fi
 
 [ -d "${BACKUP_ROOT}" ] || \mkdir -p "${BACKUP_ROOT}"
 [ -d "${BACKUP_ROOT}/boot" ] || \mkdir -p "${BACKUP_ROOT}/boot"
 
-if ! eval '$copy "${KISS_ROOT}/boot" "${BACKUP_ROOT}/"'; then
-    echo "Failed to copy '${KISS_ROOT}/boot'"
-    exit 1
+if ! eval '$copy_way "${KISS_ROOT}/boot" "${BACKUP_ROOT}/"'; then
+	echo "Failed to copy_way '${KISS_ROOT}/boot'"
+	exit 1
 else
-    echo "Succeeded in copying '${KISS_ROOT}/boot'"
+	echo "Succeeded in copying '${KISS_ROOT}/boot'"
 fi
 
 [ -d "${BACKUP_ROOT}/etc" ] || \mkdir -p "${BACKUP_ROOT}/etc"
 
-if ! eval '$copy "${KISS_ROOT}/etc" "${BACKUP_ROOT}/"'; then
-    echo "Failed to copy '${KISS_ROOT}/etc'"
-    exit 1
+if ! eval '$copy_way "${KISS_ROOT}/etc" "${BACKUP_ROOT}/"'; then
+	echo "Failed to copy '${KISS_ROOT}/etc'"
+	exit 1
 else
-    echo "Succeeded in copying '${KISS_ROOT}/etc'"
+	echo "Succeeded in copying '${KISS_ROOT}/etc'"
 fi
 
 [ -d "${BACKUP_ROOT}/usr" ] || \mkdir -p "${BACKUP_ROOT}/usr"
 
 cd  "${KISS_ROOT}/usr"
 for dir in $(doas \ls -1 "${KISS_ROOT}/usr"); do
-    [ ! -d "$dir" ] || [ "$dir" = "src" ] || [ -L "$dir" ] || {
-        if ! eval '$copy "${KISS_ROOT}/usr/$dir" "${BACKUP_ROOT}/usr/"'; then
-            echo "Failed to copy '${KISS_ROOT}/usr/$dir'"
-            exit 1
-        else
-            echo "Succeeded in copying '${KISS_ROOT}/usr/$dir'"
-        fi
-    }
+	[ ! -d "$dir" ] || [ "$dir" = "src" ] || [ -L "$dir" ] || {
+		if ! eval '$copy_way "${KISS_ROOT}/usr/$dir" "${BACKUP_ROOT}/usr/"'; then
+			echo "Failed to copy '${KISS_ROOT}/usr/$dir'"
+			exit 1
+		else
+			echo "Succeeded in copying '${KISS_ROOT}/usr/$dir'"
+		fi
+	}
 done
 
-[ -d "${BACKUP_ROOT}/var/db/kiss/installed" ] || \mkdir -p "${BACKUP_ROOT}/var/db/kiss/installed"
+[ -d "${BACKUP_ROOT}/var/db/installed" ] || \mkdir -p "${BACKUP_ROOT}/var/db/installed"
 
 # Don't delete system database
 if [ "$(/usr/bin/whoami)" = "root" ]; then
-    copy="rsync -aqz"
+	copy_way="rsync -aqzpogDX"
 else
-    copy="doas rsync -aqz"
+	copy_way="doas rsync -aqzpogDX"
 fi
 
-if ! eval '$copy "${KISS_ROOT}/var/db/kiss/installed" "${BACKUP_ROOT}/var/db/kiss/"'; then
-    echo "Failed to copy '${KISS_ROOT}/var/db/kiss/installed'"
-    exit 1
+if ! eval '$copy_way "${KISS_ROOT}/var/db/installed" "${BACKUP_ROOT}/var/db/"'; then
+	echo "Failed to copy '${KISS_ROOT}/var/db/installed'"
+	exit 1
 else
-    echo "Succeeded in copying '${KISS_ROOT}/var/db/kiss/installed'"
+	echo "Succeeded in copying '${KISS_ROOT}/var/db/installed'"
 fi
 
 sync
diff --git a/local/bin/q b/local/bin/q
--- a/local/bin/q
+++ b/local/bin/q
@@ -11,47 +11,47 @@
 
 # do not use single quotes for $1 in []
 if [ -z "${1}" ]; then
-    printf "Input target pls\n"; exit 1;
+	printf "Input target pls\n"; exit 1;
 else
-    index=0
-    target="${1}"
-    selected=
-    ver_selected=
-    sub_ver_selected=
-    packages="$(find "/var/db/kiss" \( -type d -o -type l \) -name "${target}")"
-    for pack in $packages
-    do
-        [ -d "$pack" ] && [ -f "$pack/version" ] && {
-            read -r ver sub_ver 2>/dev/null < "$pack/version" || {
-                printf "%s\n" "Failed to read version file ($pack/version)"
-                exit 1
-            }
-            printf "%-4d %-9s %-4s %s\n" $((index)) "$ver" "$sub_ver" "$pack"
-            if [ -n "$2" ] && [ $index = $2 ]; then
-                selected="$pack"
-                ver_selected="$ver"
-                sub_ver_selected="$sub_ver"
-            fi
-            index=$(($index + 1))
-        }
-    done
-    if [ -n "$selected" ]; then
-        printf "\n%s\n%-4d %-9s %-4s %s\n\n" "Selected package:" $2  "$ver_selected" "$sub_ver_selected" "$selected"
-        dir="$(dirname "$selected")"
-        base="$(basename "$selected")"
-        if [ -z "${USE_GMAKE}" ]; then
-            printf "\n%s\n\n" "BSD make used"
-        else
-            printf "\n%s\n\n" "GNU make used"
-            build_root="${HOME}/.cache/kiss/proc/$base"
-            [ ! -d "${build_root}/bin" ] && mkdir -p "${build_root}/bin"
-            [ "$(readlink "${build_root}/bin/gunzip")" != "/usr/bin/pigz"  ] && \ln -sf "/usr/bin/pigz"  "${build_root}/bin/gunzip"
-            [ "$(readlink "${build_root}/bin/make")"   != "/usr/bin/gmake" ] && \ln -sf "/usr/bin/gmake" "${build_root}/bin/make"
-            export PATH="${build_root}/bin:$PATH"
-        fi
-        export KISS_PATH=$dir
-        /usr/bin/kiss c $base 2>&1 > /dev/stderr &&
-        /usr/bin/kiss b $base 2>&1 > /dev/stderr &&
-        /usr/bin/kiss i $base
-    fi
+	index=0
+	target="${1}"
+	selected=
+	ver_selected=
+	sub_ver_selected=
+	packages="$(doas find -L "/var/db/kiss" \( -type d -o -type l \) -name "${target}")"
+	for pack in $packages
+	do
+		[ -d "$pack" ] && [ -f "$pack/version" ] && {
+			read -r ver sub_ver 2>/dev/null < "$pack/version" || {
+				printf "%s\n" "Failed to read version file ($pack/version)"
+				exit 1
+			}
+			printf "%-4d %-9s %-4s %s\n" $((index)) "$ver" "$sub_ver" "$pack"
+			if [ -n "$2" ] && [ $index = $2 ]; then
+				selected="$pack"
+				ver_selected="$ver"
+				sub_ver_selected="$sub_ver"
+			fi
+			index=$(($index + 1))
+		}
+	done
+	if [ -n "$selected" ]; then
+		printf "\n%s\n%-4d %-9s %-4s %s\n\n" "Selected package:" $2  "$ver_selected" "$sub_ver_selected" "$selected"
+		dir="$(dirname "$selected")"
+		base="$(basename "$selected")"
+		if [ -z "${USE_GMAKE}" ]; then
+			printf "\n%s\n\n" "BSD make used"
+		else
+			printf "\n%s\n\n" "GNU make used"
+			build_root="${HOME}/.cache/kiss/proc/$base"
+			[ ! -d "${build_root}/bin" ] && mkdir -p "${build_root}/bin"
+			[ "$(readlink "${build_root}/bin/gunzip")" != "/usr/bin/pigz"  ] && \ln -sf "/usr/bin/pigz"  "${build_root}/bin/gunzip"
+			[ "$(readlink "${build_root}/bin/make")"   != "/usr/bin/gmake" ] && \ln -sf "/usr/bin/gmake" "${build_root}/bin/make"
+			export PATH="${build_root}/bin:$PATH"
+		fi
+		export KISS_PATH=$dir
+		/usr/bin/kiss c $base 2>&1 > /dev/stderr &&
+		/usr/bin/kiss b $base 2>&1 > /dev/stderr &&
+		/usr/bin/kiss i $base
+	fi
 fi
diff --git a/local/bin/restore b/local/bin/restore
--- a/local/bin/restore
+++ b/local/bin/restore
@@ -1,29 +1,29 @@
-#!/bin/sh
+#! /bin/sh
 
 BACKUP_ROOT="$HOME/downloads/linux/kissllm/chroot-x86_64"
 
 TARET_ROOT="/mnt/kiss"
 
 if [ "${HOSTNAME}" = "kiss" ]; then
-    TARET_ROOT=""
+	TARET_ROOT=""
 else
-    doas /mnt/load-kiss
+	doas /mnt/load-kiss
 fi
 
 if [ "$(/usr/bin/whoami)" = "root" ]; then
-    copy="rsync -aqz"
+	copy="rsync -aqz"
 else
-    copy="doas rsync -aqz"
+	copy="doas rsync -aqz"
 fi
 
 cd "${BACKUP_ROOT}"
 doas chattr -i /etc/resolv.conf
 for dir in $(doas \ls -1 "${BACKUP_ROOT}"); do
-    if ! eval '$copy "${BACKUP_ROOT}/$dir" "${TARET_ROOT}/"'; then
-        echo "Failed to copy '${BACKUP_ROOT}/$dir'"
-        exit 1
-    else
-        echo "Succeeded in copying '${BACKUP_ROOT}/$dir'"
-    fi
+	if ! eval '$copy "${BACKUP_ROOT}/$dir" "${TARET_ROOT}/"'; then
+		echo "Failed to copy '${BACKUP_ROOT}/$dir'"
+		exit 1
+	else
+		echo "Succeeded in copying '${BACKUP_ROOT}/$dir'"
+	fi
 done
 doas chattr +i /etc/resolv.conf
diff --git a/local/bin/wpa b/local/bin/wpa
--- a/local/bin/wpa
+++ b/local/bin/wpa
@@ -1,65 +1,65 @@
 #!/bin/sh
 
 { [ -z "$1" ] || [ "$1" != "down" ]; } && {
-    [ $(id -u) -ne "0" ] || { echo "We don't save hardcoded config files in root user's folder"; exit 1; }
-    config="$1"
-    [ -n "$1" ] && [ -e "$1" ] ||
-    config=$HOME/.config/wpa_supplicant/wpa_supplicant.conf
-    echo "\$config = $config"
-    [ -f "$config" ] ||
-    { echo "Input valid \$1 for switch, please"; exit 1; }
+	[ $(id -u) -ne "0" ] || { echo "We don't save hardcoded config files in root user's folder"; exit 1; }
+	config="$1"
+	[ -n "$1" ] && [ -e "$1" ] ||
+	config=$HOME/.config/wpa_supplicant/wpa_supplicant.conf
+	echo "\$config = $config"
+	[ -f "$config" ] ||
+	{ echo "Input valid \$1 for switch, please"; exit 1; }
 
 
-    address="$(lspci -nnk | grep wifi | awk "{print \$1}")"
-    # 00:14.3
-    for item in $(ls -1 /sys/class/net); do
-        real_name="$(doas readlink -f "/sys/class/net/${item%\@}")"
-        [ -n "${real_name##*"$address"*}" ] || interface="${item%\@}"
-    done
+	address="$(lspci -nnk | grep wifi | awk "{print \$1}")"
+	# 00:14.3
+	for item in $(ls -1 /sys/class/net); do
+		real_name="$(doas readlink -f "/sys/class/net/${item%\@}")"
+		[ -n "${real_name##*"$address"*}" ] || interface="${item%\@}"
+	done
 
-    # interface=$(\ls /sys/class/ieee80211/*/device/net > /dev/null)
+	# interface=$(\ls /sys/class/ieee80211/*/device/net > /dev/null)
 
-    [ -n "$interface" ] || interface=$(iw dev | awk '$1=="Interface"{print $2}')
-    echo "\$interface = $interface"
-    wpa_list="$(ps -ef | grep wpa_supplicant | grep -v grep | grep -v $$ | awk "{print \$1}" | tr -d ' ')"
-    for wpa in $wpa_list; do doas kill -9 $wpa; done
+	[ -n "$interface" ] || interface=$(iw dev | awk '$1=="Interface"{print $2}')
+	echo "\$interface = $interface"
+	wpa_list="$(ps -ef | grep wpa_supplicant | grep -v grep | grep -v $$ | awk "{print \$1}" | tr -d ' ')"
+	for wpa in $wpa_list; do doas kill -9 $wpa; done
 
-    # https://www.linuxquestions.org/questions/slackware-14/wpa_supplicant-failed-to-initialize-driver-4175668012/
-    # bring up the ethernet adapter
-    doas /sbin/ip link set dev $interface up >> $HOME/.config/wpa_supplicant/.wpa.log 2>&1
+	# https://www.linuxquestions.org/questions/slackware-14/wpa_supplicant-failed-to-initialize-driver-4175668012/
+	# bring up the ethernet adapter
+	doas /sbin/ip link set dev $interface up >> $HOME/.config/wpa_supplicant/.wpa.log 2>&1
 
-    # flush its configuration
-    doas /sbin/ip address flush dev $interface >> $HOME/.config/wpa_supplicant/.wpa.log 2>&1
+	# flush its configuration
+	doas /sbin/ip address flush dev $interface >> $HOME/.config/wpa_supplicant/.wpa.log 2>&1
 
-    # you might need an IP address before doing the IEEE 802.1X authentication with wpa_supplicant
-    # /sbin/dhclient eth0
-    doas su dhcpcd /sbin/dhcpcd $interface >> $HOME/.config/wpa_supplicant/.wpa.log 2>&1
+	# you might need an IP address before doing the IEEE 802.1X authentication with wpa_supplicant
+	# /sbin/dhclient eth0
+	doas su dhcpcd /sbin/dhcpcd $interface >> $HOME/.config/wpa_supplicant/.wpa.log 2>&1
 
-    doas touch /tmp/wpa.lock
-    # then run wpa_supplicant
-    # doas wpa_supplicant -D nl80211 -B -i $interface -c $HOME/.config/wpa_supplicant/wpa_supplicant.conf
-    doas wpa_supplicant -D nl80211 -B -i $interface -c $config > $HOME/.config/wpa_supplicant/.wpa.log 2>&1 &
-    sleep 3s
-    doas su dhcpcd /sbin/dhcpcd $interface >> $HOME/.config/wpa_supplicant/.wpa.log 2>&1
-    iwconfig
-    :
+	doas touch /tmp/wpa.lock
+	# then run wpa_supplicant
+	# doas wpa_supplicant -D nl80211 -B -i $interface -c $HOME/.config/wpa_supplicant/wpa_supplicant.conf
+	doas wpa_supplicant -D nl80211 -B -i $interface -c $config > $HOME/.config/wpa_supplicant/.wpa.log 2>&1 &
+	sleep 3s
+	doas su dhcpcd /sbin/dhcpcd $interface >> $HOME/.config/wpa_supplicant/.wpa.log 2>&1
+	iwconfig
+	:
 } || {
-    wpa_list="$(ps -ef | grep wpa_supplicant | grep -v grep | awk "{print \$1}" | tr -d ' ')"
-    for wpa in $wpa_list; do doas kill -9 $wpa; done
-    # doas /usr/bin/find /sys/class/ -name enp2s0
-    # /sys/class/net/enp2s0
-    # interface="enp2s0"
-    address="$(lspci -nnk | grep alx | awk "{print \$1}")"
-    # 02:00.0
-    for item in $(ls -1 /sys/class/net); do
-        real_name="$(doas readlink -f "/sys/class/net/${item%\@}")"
-        [ -n "${real_name##*"$address"*}" ] || interface="${item%\@}"
-    done
-    # interface="eth0"
-    echo "\$interface = $interface"
-    doas sv restart dhcpcd
-    doas /sbin/ip link set dev "$interface" up
-    doas /sbin/ip address flush dev "$interface"
-    doas su dhcpcd /sbin/dhcpcd "$interface"
-    ifconfig -a
+	wpa_list="$(ps -ef | grep wpa_supplicant | grep -v grep | awk "{print \$1}" | tr -d ' ')"
+	for wpa in $wpa_list; do doas kill -9 $wpa; done
+	# doas /usr/bin/find /sys/class/ -name enp2s0
+	# /sys/class/net/enp2s0
+	# interface="enp2s0"
+	address="$(lspci -nnk | grep alx | awk "{print \$1}")"
+	# 02:00.0
+	for item in $(ls -1 /sys/class/net); do
+		real_name="$(doas readlink -f "/sys/class/net/${item%\@}")"
+		[ -n "${real_name##*"$address"*}" ] || interface="${item%\@}"
+	done
+	# interface="eth0"
+	echo "\$interface = $interface"
+	doas sv restart dhcpcd
+	doas /sbin/ip link set dev "$interface" up
+	doas /sbin/ip address flush dev "$interface"
+	doas su dhcpcd /sbin/dhcpcd "$interface"
+	ifconfig -a
 }
